### ISSUE TITLE
Infill/wall overlap specifically for bridges 

### ISSUE THREAD

**Issue by hutje** [SoftFever/OrcaSlicer#1067]
**Is your feature request related to a problem? Please describe.**
When changing the infill/wall overlap, it also changes the normal infill overlap. But for bridges with a bigger gap, it is necessary to have more overlap. 

**Describe the solution you'd like**
An option to change the overlap for bridges without the need to change all the overlap.

**Additional context**
As you can see I set overlap to 110% to ensure a good anchorpoint. But for the other lines it is too much. (I have set the bridge-flow to 0.7 and 70% density)
![Infill wall overlap](https://github.com/SoftFever/OrcaSlicer/assets/15308350/b83e8ecb-14ce-406a-bc08-6e4a1089daf1)

**Comment by ncr** [comment]
I'm having the same issue with bridges and while the infill/wall setting helps, it would be very useful to have such setting specifially for the bridges. We have some specific temperature / fan settings that we can't tweak but still need sound bridges and this is about the only setting that helps but on the other hand it messes up the infill a bit.

**Comment by duerk-de** [comment]
I would like to add a comment since I am also facing this issue and did not find any suitable workaroud, yet.

The first thing I noticed is, that switching off sparse infill changes things (see images):
![Screenshot at 2024-10-21 08-21-10](https://github.com/user-attachments/assets/f1592f6e-24e0-452f-8c92-d9e76eecc13f)
![Screenshot at 2024-10-21 08-21-50](https://github.com/user-attachments/assets/bd745f05-42cf-49bb-9949-303bd73ebb2f)
The sparse infill is substituted by a bridge!

Nevertheless on thin walls there is practically no overlap.

Increasing Infillwall overlap does not add any overlap to thick walls:
![Screenshot at 2024-10-21 08-31-43](https://github.com/user-attachments/assets/716f48dd-8b60-4100-9849-6b84224d585c)

**Comment by Eerier** [comment]
This is a great idea and i would certainly use it
