### ISSUE TITLE
Overhangs and gap fill velocities are not subject to the maximum volume flow limit

### ISSUE THREAD

**Issue by FillPavS** [SoftFever/OrcaSlicer#1079]
Overhangs and gap fill velocities are not subject to the maximum volume flow limit in the plastic settings. This causes plugging on soft plastics that cannot be printed quickly. This can be changed manually in the speed settings, but it seems to me that the flow limit should limit all speeds.

![Снимок экрана (112)](https://github.com/SoftFever/OrcaSlicer/assets/17209082/cdedff03-d53f-444e-b063-ed2a444f4ae0)
![Снимок экрана (111)](https://github.com/SoftFever/OrcaSlicer/assets/17209082/65096a74-d11f-451a-8d57-3cb21a6a83d0)

**Comment by hliebscher** [comment]
witch os witch slicer ? and witch model file ?

**Comment by FillPavS** [comment]
UPD. Sorry, bridges are fine. Only overhangs and gap fill

**Comment by FBrand** [comment]
Same Bug, flow of ~30mm³/s instead of 4mm³.
OS: Manjaro Linux 22.1
Orca Slicer 1.6.3 (AppImage)
Model: 3DBenchy

![image](https://github.com/SoftFever/OrcaSlicer/assets/14114342/3b9bd355-5722-42f9-8923-f3717d0c7e62)

![image](https://github.com/SoftFever/OrcaSlicer/assets/14114342/cc5b63f4-861a-409f-b3e3-1eeb6a6cf222)

**Comment by hendrikhaehnel** [comment]
Seems to be the same issue as: https://github.com/SoftFever/OrcaSlicer/issues/852

Workaround: Use "classic mode" for slow down on overhangs. Max. flow is respected in that mode.
