### ISSUE TITLE
Allow drag and drop 3D files to any screen, not only just the prepare screen

### ISSUE THREAD

**Issue by Photogad** [SoftFever/OrcaSlicer#1096]
**Is your feature request related to a problem? Please describe.**
I like to drag-and-drop (windows) 3MF or STL file from my desktop into Bambu Studio. However, it only allows drag-and-drop when you are on the "prepare" screen. I think it would be better if you also allowed drag and drop on the "main" screen that opens when bambu studio opens. This would save an extra step and be more quicker for user. And, sometimes I forget to change to "prepare" screen before drag and drop, and this can be annoying.

**Describe the solution you'd like**
Allow user to drag-and-drop 3MF or STL/STEP file into the program no matter which screen is open in the program.

**Describe alternatives you've considered**
No alternative

**Additional context**

SHOULD BE 
![Screenshot 2023-05-19 113316](https://github.com/SoftFever/OrcaSlicer/assets/18505956/8279fed0-6df0-4bc2-93df-a1e9bfe4dc0b)
ABLE TO DRAG AND DROP FILES HERE:

BUT CAN CURRENTLY ONLY DRAG AND DROP FILES HERE:
![Screenshot 2023-05-19 113335](https://github.com/SoftFever/OrcaSlicer/assets/18505956/9f4b3a4a-4237-4107-a65f-74c6ee0cb940)

**Comment by mydevpeeps** [comment]
I have noticed that even when I have the prepare screen open, and have 2 plates up, if I have plate A selected but drag the item to plate B it puts it on plate A anyway. This seems intentional to me. I like the idea, though, of having it kick it back to the prepare tab from any other tab. It could even pop up a warning first like when you pull in a 3MF with other stuff in there just to be sure you meant to do that..
