### ISSUE TITLE
Texture BED problem

### ISSUE THREAD

**Issue by iphonetik** [SoftFever/OrcaSlicer#1177]
When I start Oscar Slicer, I set up my printer and then when the bed area where the parts are worked on appears, I see a black image as if it were a texture.

I have no idea how to make it appear like in version 1.62.

![2023-05-29 09_40_42-Untitled](https://github.com/SoftFever/OrcaSlicer/assets/37641823/b6484875-1855-45c0-b09b-3405e193ce4f)
![2023-05-29 09_28_57-Window](https://github.com/SoftFever/OrcaSlicer/assets/37641823/b08edc98-e494-4821-833a-ec4cb5509774)

**Printer model**
Ender 3 V2 with Sprite Pro
 -Windows 10
 - Orca Slicer 1.63

**Comment by iphonetik** [comment]
If I select a generic profile, it works fine. I cannot select the profile for my Ender 3 V2 because the issue occurs again.
![2023-05-29 10_03_07-Window](https://github.com/SoftFever/OrcaSlicer/assets/37641823/82474668-cbe3-450b-b65c-78095f35eb78)

**Comment by fr3ak2402** [comment]
@iphonetik 

I have just done this and the texture appears normal to me.

![Screenshot 2023-05-29 161115](https://github.com/SoftFever/OrcaSlicer/assets/96239814/4d53e163-5b0d-43c6-a37e-8179ffd168f6)

But I also have to say that I already have the latest profiles, etc., because I'm working on them at the moment.

But actually the texture should already look like in your picture.

Can you please open the following folder in the OrcaSlicer installation folder and take a screenshot?

/resources/profiles/creality
In this folder there should be a file like the following:
creality_ender3v2_buildplate_model.stl
creality_ender3v2_buildplate_texture.png

**Comment by iphonetik** [comment]
The files appear. I tried loading them manually, but nothing happens. I deleted the configuration folder and started over, but the same thing happens.

![2023-05-29 10_34_43-Untitled](https://github.com/SoftFever/OrcaSlicer/assets/37641823/08cd5c17-d876-4bd3-8ca2-fba4d7a6a2a7)
![2023-05-29 10_32_00-Creality](https://github.com/SoftFever/OrcaSlicer/assets/37641823/6c34deac-b101-4d43-bc58-28027cfb0b82)

**Comment by SoftFever** [comment]
@iphonetik 
What GPU do you have in your machine? Is it AMD?
I found some AMD driver didn't do well with non regular size texture.
Can you override the texture this modified textures and see if it works?
[creality_ender3v2_buildplate_texture.zip](https://github.com/SoftFever/OrcaSlicer/files/11592607/creality_ender3v2_buildplate_texture.zip)

**Comment by iphonetik** [comment]
Yes i have RX480 GPU i try the new texture thanks!

**Comment by iphonetik** [comment]
I solve the problem thanks!
![2023-05-29 11_29_45-Window](https://github.com/SoftFever/OrcaSlicer/assets/37641823/6daf874a-dcad-4134-82d6-71e0d92c7ff4)

**Comment by iphonetik** [comment]
Thanks for support and Keep up the good work, I love Orca Slicer.
