### ISSUE TITLE
Flow Rate Ignored

### ISSUE THREAD

**Issue by Highlander-bdj** [SoftFever/OrcaSlicer#1216]
Filament flow max volume rates are ignored unless "classic mode" for overhang speed is selected.

![image](https://github.com/SoftFever/OrcaSlicer/assets/78763438/acfc9506-f82b-4ed7-919a-54ae0e1ef7f7)

![image](https://github.com/SoftFever/OrcaSlicer/assets/78763438/87bb9afc-d751-40a4-b34d-39b76054abbb)

**Comment by RydellV** [comment]
Can confirm this as well. Tried making a TPU profile by just limiting the volumetric flow rate to 2 and after slicing there were  several overhangs at 14. Classic mode fixed it.

**Comment by Marijn1250** [comment]
Same here. I tried switching to classis mode and that fixed the flow issue. 
I then switched back to Arachne mode and sliced again. The problem was still fixed. 
Maybe you can test the same. 

- Go to Classic Mode and slice.
- Check preview - select Flow 
- Go back to Arachne Mode and slice
- Check the preview again - Flow

**Comment by PrincessLuna2253** [comment]
Confirming that I am also seeing this issue in version 1.6.4. The workaround of slicing in classic mode and then turning classic mode off and slicing again does not work for me.

**Comment by hatkyinc2** [comment]
Sounds like the same issue as https://github.com/SoftFever/OrcaSlicer/issues/2033

I've tried classic mode now with 1.8 beta2, doesn't seem to work
