### ISSUE TITLE
Fusion360 export stl using external application.

### ISSUE THREAD

**Issue by favoritewky** [SoftFever/OrcaSlicer#1351]
**Is your feature request related to a problem? Please describe.**
Fusion360 export stl using external application like *PRUSA* can work good.

**Describe the solution you'd like**
But the orcaslicer can open a stl as the exe paramerter.

**Describe alternatives you've considered**
Can you make it work?

**Additional context**

**Comment by julie777** [comment]
This should be considered as part of the single instance option. 
When the application is started by Fusion 360 it uses a command line `.../path/OrcaSlicer.exe STL_file_path_from_F360`.

This is also what happens when you drag a file to the slicer window, or when you use "open with" or have the file extension bound to the application.

Orca/Studio do not handle any of these well on Windows 10.

**Comment by favoritewky** [comment]
> This should be considered as part of the single instance option. When the application is started by Fusion 360 it uses a command line `.../path/OrcaSlicer.exe STL_file_path_from_F360`.
> 
> This is also what happens when you drag a file to the slicer window, or when you use "open with" or have the file extension bound to the application.
> 
> Orca/Studio do not handle any of these well on Windows 10.

Yes， *PRUSA* can handle this well so can you implement this please?
