### ISSUE TITLE
Make Overhang Printable Feature [$300 Bounty]

### ISSUE THREAD

**Issue by odie5533** [SoftFever/OrcaSlicer#1534]
**I offer a $300 bounty for the implementation of this feature with results comparable to those below, as determined by OrcaSlicer maintainers.**

Cura has feature called Make Overhang Printable in their CuraEngine. Cura includes two adjustment settings: Maximum Model Angle (conical_overhang_angle) and Maximum Overhang Hole Area (conical_overhang_hole_size).

Cura ConicalOverhang algorithm: https://github.com/Ultimaker/CuraEngine/blob/main/src/ConicalOverhang.cpp

The setting must be used judiciously, but it saves having to use supports or modify the model. It has a wide range of uses from organics like statues, functional prints, hard shapes, and soft shapes. As long as the changes are subtle enough or in unimportant places, it can be a godsend since it avoids supports, saving print time and cleanup.

My attempt. I did not get very far with the algorithm as I do not understand the libslic3r objects. https://github.com/odie5533/OrcaSlicer/pull/1/files

![249346523-dff97ea9-d14e-43b4-8264-b622716d9718](https://github.com/SoftFever/OrcaSlicer/assets/371066/880447b2-c54e-4d9c-ab08-e554a7c2b040)

---

Knob: https://www.thingiverse.com/thing:665410/files

![249791214-159bc73b-ea04-4e3c-87a5-d22632685e8a](https://github.com/SoftFever/OrcaSlicer/assets/371066/b56324ec-0b61-4af3-8fb4-e3db94eaf823)

---

Yoda: https://www.thingiverse.com/thing:276994/files

![249797380-7be1c2dc-2921-44bd-a031-56a2d86bf90c](https://github.com/SoftFever/OrcaSlicer/assets/371066/b01578fd-634f-4880-ae7f-343ca54d9acb)
![249798090-911eed54-78d6-4e5b-9b1f-ef70824ad76a](https://github.com/SoftFever/OrcaSlicer/assets/371066/18433133-041d-4266-9d10-ebe9e6275293)

---

[Overhang Demo 20 deg.stl.zip](https://github.com/SoftFever/OrcaSlicer/files/12045825/Overhang.Demo.20.deg.stl.zip)

![20 degree overhang](https://github.com/SoftFever/OrcaSlicer/assets/371066/e25a3e85-bfc0-485e-9ea2-f31e4a62a13f)

---

[Overhang Demo.stl.zip](https://github.com/SoftFever/OrcaSlicer/files/12045826/Overhang.Demo.stl.zip) - 90 degrees

![90 degree overhang](https://github.com/SoftFever/OrcaSlicer/assets/371066/b4580486-0100-4c8a-a725-6700487dfcfc)
![90 degree overhang (2)](https://github.com/SoftFever/OrcaSlicer/assets/371066/20511b56-e1b1-423d-8f0f-4c974713e264)

**Comment by odie5533** [comment]
@Noisyfox This is incredible!!! I can't believe it's working! You are amazing!!!!!!!

I've added settings for the implementation and put up a PR #1556 

Would you be able to add the hole_size stuff to the code? The code seems a little unfinished in its current state so not sure how to clean it up exactly.

**Comment by Noisyfox** [comment]
> Would you be able to add the hole_size stuff to the code? The code seems a little unfinished in its current state so not sure how to clean it up exactly.

Yeah I will, and the code needs more testing too because I don't fully understand how libslic3r works either :p

**Comment by Noisyfox** [comment]
@odie5533 I'v done implementing the hole size part.

**Comment by odie5533** [comment]
> I am also thinking of adding this setting to modifiers, so you can apply this only to part of the model. Though this might be tricky to implement as it will make calculating the overhang support shape for different parts more complicated.

If this would be possible it would be really cool and a feature that even Cura doesn't have! Let me know what you think.

**Comment by Noisyfox** [comment]
The main problem is I couldn't figure out how the algorithm work if say the user added multiple modifiers to the same layer with different max overhang angle, since the polygon offset function cannot apply different offset values on different directions.

On the other hand, I think it's totally pointless to allow specifying different max angle value to different part of the model, what matters most is the ability to turn on & off the conical overhang feature on demand, the max angle and hole size configuration can be a shared setting for all places where this feature is enabled, which make the calculation much simpler. However, this makes the configuration UI a bit tricky to design, for example, do we want a global switch to turn this feature on, then an option in the modifier to turn it off? Or do we want the opposite? Or both? And where to put the shared max angle/hole size settings?

Any suggestion will be appreciated.

**Comment by foreachthing** [comment]
@Noisyfox 
my 2¢:
* "globally" enable/disable M.O.P.F. and set angle.
  * I'd put it in "others" -> "Special mode".
* have modifiers to be able to _disable_ M.O.P.F.
* nice-to-have: enable/disable it per part

If you enable M.O.P.F., you might want to turn it off somewhere locally. No need to enable it on a "small" section, I think.

**Comment by Noisyfox** [comment]
> you might want to turn it off somewhere locally. No need to enable it on a "small" section, I think.

I think you are right, as there should be more overhangs than bridges for models which the M.O.P.F. is useful and it shouldn't be too difficult to apply modifiers to those bridges.

> * nice-to-have: enable/disable it per part

This is already supported btw, you can change this setting per object.

**Comment by Noisyfox** [comment]
![image](https://github.com/SoftFever/OrcaSlicer/assets/1537155/e8b9605c-9423-43d1-b3e3-5bbe575b7f79)
![image](https://github.com/SoftFever/OrcaSlicer/assets/1537155/3f44b319-ea9f-420d-ae3b-681bfb084b4b)

Now you can disable this per modifier.

**Comment by odie5533** [comment]
PR #1615 closes this

Bounty paid to @Noisyfox and also made a donation on ko-fi to @SoftFever 

Thank you both so much for working on this feature!

**Comment by rjmessing** [comment]
I've run into a problem with the make overhangs printable.  If I enable it for some parts any internal geometry disappears.  This part of a spool winder I'm making, the overhang is pretty steep and I thought I'd try making them printable.  As you can see the central area for the screw gets removed.

![Make Overhang printable disabled](https://github.com/SoftFever/OrcaSlicer/assets/69949206/733f80ec-cd5b-468c-b12f-a0d155a186bd)
![Make Overhang printable enabled](https://github.com/SoftFever/OrcaSlicer/assets/69949206/5c159e28-aef8-4eaa-a28d-6c23216b2787)

**Comment by triangleman83** [comment]
I am working on a model that has some challenging overhangs and this feature is improving its printability greatly. I am also coloring a few layers at the top of the model and I found that having this option enabled caused the slicer to create too many toolpaths through the colored portion all the way down through the model. This led to needless color changes throughout the infill which was now colored walls. I found that creating a modifier over the colored area to disable the feature solved the issue. I did not think this necessitated a bug report myself since it could just be two conflicting orders given to the slicer and also since the modifier solves the issue. I can provide more information if needed but wanted to make this comment for posterity in case anyone else has trouble with coloring with this option enabled. If the coloring is also required on the areas being modified, that may not be solvable with a modifier though. Thank you for the great feature!
