### ISSUE TITLE
Allow a lower temperature during temperature calibration

### ISSUE THREAD

**Issue by SvenBunge** [SoftFever/OrcaSlicer#1541]
The supported temperature range in the temperature calibration is 180-350°C. Please enable also lower temps (in custom settings) to test filaments like the "Extrudr Dark Wood" Filament with a suggested temp range of 170-190°C.
I suggest to set the minimum value to 160°C.

**Comment by Noxoreos** [comment]
Since this is not needed very often, you could add the 170°C and 160°C models on top of the generated tower and add custom gcode to change the temperature in the preview section by scrolling the top slider to the specific element and use the "Add custom G-code" entry in the right click menu. 

See screenshot: ![screenshot](https://github.com/SoftFever/OrcaSlicer/assets/29963291/fc716b4f-1e8b-4bc0-bdf4-aad477a7e8ed)
