### ISSUE TITLE
Calibration test don't allow values in the wiki itself

### ISSUE THREAD

**Issue by nagisasatoru36** [SoftFever/OrcaSlicer#1644]
Bug : 

During the calibration of retraction (from calibration tab) the default values (also shown in the wiki) isn't allowed (0 mm start / 2mm end / 
0.1mm/mm step)

![too_much](https://github.com/SoftFever/OrcaSlicer/assets/28569461/c5a8e49a-7555-4e0d-bad7-ccb72e876a86)

And the prompt showing error doesn't match the wiki and default ; Start > 0 is not verified in default and wiki (here  >= 0). Plus there a flaw in the prompt : step can be equal to 0 (meaning no increment during test ?? So no test at all if increment = 0)

And even after verified prompt request it doesn't work : 

![laputain](https://github.com/SoftFever/OrcaSlicer/assets/28569461/4d497726-eb66-4e93-adff-ef1cfb5be6f6)

Reproduce : 

Launch a calibration test.

Expected behavior : 
 
That you could manage a retractation calibration test with default values/coherent values.

**Comment by SoftFever** [comment]
@nagisasatoru36 
if you are using France language, the 0.1 step number should be `0,1`, not `0.1`
![Screenshot 2023-07-31 194259](https://github.com/SoftFever/OrcaSlicer/assets/103989404/0441791e-08c6-4a4c-aec4-770b8b9e8348)

**Comment by nagisasatoru36** [comment]
> @nagisasatoru36 if you are using France language, the 0.1 step number should be `0,1`, not `0.1` ![Screenshot 2023-07-31 194259](https://user-images.githubusercontent.com/103989404/257208761-0441791e-08c6-4a4c-aec4-770b8b9e8348.png)

Indeed! It works with colonl!

![francais](https://github.com/SoftFever/OrcaSlicer/assets/28569461/cb30f1ba-fdc2-435d-8439-d84ea07bce99)

But that a poor way to code user input in that scenario. Other input ignore the '.' and replace it with ',' in profile (for example if i set 0.2 at layer height and press [enter] it becomes 0,2 and accept value. So that a langage isssue (We french aren't moron and understand the '.' syntax lol. Maybe we should just set '.' as every single french program that I use anyway).

So here is a langage bug related.

**Comment by SoftFever** [comment]
@nagisasatoru36 
Hahaha, that will definitely make the programmer's life easier ;)
I actually released a hotfix to fix this exact issue
![image](https://github.com/SoftFever/OrcaSlicer/assets/103989404/1ea6fdaa-6a32-4ddd-bea0-21e910790d08)

Joke aside, I believe it reads your system's setting, if you change the Decimal symbol to `.` in your system setting, it should be automatically accept `.`. instead of `,`.
But I didn't test it myself.
![image](https://github.com/SoftFever/OrcaSlicer/assets/103989404/b9aac7ce-9666-4f2b-beba-a6767502288e)
