### ISSUE TITLE
Quality issue with "Single wall on top surface" with 1.6.4 beta

### ISSUE THREAD

**Issue by Hammer57** [SoftFever/OrcaSlicer#1680]
1.6.4 removes too many inner walls with this setting on. Leading to a rougher surface.

Left 1.6.4 Beta, Right 1.6.3

"Single wall on top surface" On
![OneWallOn](https://github.com/SoftFever/OrcaSlicer/assets/94201981/03a5c4a3-24da-4285-91bc-4c23e601a4ab)
"Single wall on top surface" Off
![OneWallOff](https://github.com/SoftFever/OrcaSlicer/assets/94201981/85ed8f4f-e123-4c6f-84f2-67f31ec5112e)
"Single wall on top surface" On
![IMG_1762](https://github.com/SoftFever/OrcaSlicer/assets/94201981/db3ad776-6dca-4a2a-bc22-411944a770d3)

STL
[Ghost.zip](https://github.com/SoftFever/OrcaSlicer/files/12256926/Ghost.zip)

**Comment by Noisyfox** [comment]
Well unless you fix your printer's top layer quality, the extra walls won't really help. Your model just happened to have your upper layers cover the lower walls. If you print models like the benchy then your top surfaces will have low quality regardless.

**Comment by Hammer57** [comment]
Don´t think that the problem is my printers top layer. 
These are from 1.6.3. Definitely better as the top of the Ghost with 1.6.4.
![IMG_1763](https://github.com/SoftFever/OrcaSlicer/assets/94201981/11ad68b2-d2aa-4536-8b6d-d50fd6ac015d)
![IMG_1764](https://github.com/SoftFever/OrcaSlicer/assets/94201981/c07c5cb7-74cf-499c-bfb9-42673ba1d866)
![IMG_1765](https://github.com/SoftFever/OrcaSlicer/assets/94201981/88628f4d-b588-46c6-b43e-612d0291e411)


Not yet printed a Benchy or Calicube with 1.6.4

**Comment by Noisyfox** [comment]
Try classic wall generator and see if the same issue presents with Single wall on top surface turned on.

**Comment by Hammer57** [comment]
Better but still not like 1.6.3.
![IMG_1767](https://github.com/SoftFever/OrcaSlicer/assets/94201981/bf69fad8-762c-4060-8930-c7d073931016)

Another thing: Could it be that the setting did not work as intended in 1.6.3 with Arachne? 
With Classic "one wall" On the preview looks the same in 1.6.4 and in 1.6.3. 
With Arachne there was only a minor difference between On/Off in 1.6.3 (screenshots in first post) in comparison to 1.6.4

**Comment by locki-cz** [comment]
@Hammer57 Problem is you dont understand how it works, It set one perimeter on all top surfaces, in some cases like this on it will look every time worse thena more perimeters, you should use there modifiers if it is possbile like in prusaslicer and set it just on last layer or dont use it on that object at all OR use concetric top layer fill. Concentric looks better on round objects :)

**Comment by Noisyfox** [comment]
Looks like you have too much overlap between the infill and the walls, could you try decreasing it? Or maybe change the wall order to infill first?

**Comment by Hammer57** [comment]
@locki-cz I do understand the concept, I was just irritated, that this was a non-issue with the previous version of OrcaSlicer. But if it was not really working (as confirmed by Noisefox) explains it. Thanks for the tip with concentric top layer fill. Totally forgot about that.

@Noisyfox Thx, I´ll try that.

**Comment by Hammer57** [comment]
> Looks like you have too much overlap between the infill and the walls, could you try decreasing it? Or maybe change the wall order to infill first so the wall can cover the overlap?

Made no real difference. Left is with Infill/Outer/Inner, right is with overlap 5% instead of the default 15%

![IMG_1768](https://github.com/SoftFever/OrcaSlicer/assets/94201981/ca5b24c8-aebe-468f-904d-05b5b9f4511e)

**Comment by SoftFever** [comment]
Hi
I understand that this thread is already closed, but I still wanted to provide some comments on this matter :)

This issue has actually been persistent in the previous version of "single wall on top" as well. It didn't work well for models with slanted top surfaces, like the ghost model you mentioned. Personally, I tend to turn off this feature when printing such models.

You might not have noticed these artifacts because the 1.6.3 version didn't have the real "single wall on top" feature for the Arachne engine. It's a new implementation by @Noisyfox in the 1.6.4 beta.

Anyway, I made a small tweak to this feature. I'll release a new beta-2 build later, which will also include other bug fixes reported by users.

For comparisons:
Current effect:
![image](https://github.com/SoftFever/OrcaSlicer/assets/103989404/fcced6dd-06e1-4c70-8a2c-4f3830ba6b34)

After tweaked:
![image](https://github.com/SoftFever/OrcaSlicer/assets/103989404/e532a6e5-5292-4d1b-84f6-1964f08ce41d)

**Comment by Hammer57** [comment]
Thanks for the info. Looking forward to the second beta. Looks way better in the second pic. 

BTW: Big thanks to you and everyone involved in making this awesome piece of software. 👍

**Comment by igiannakas** [comment]
I've played around with the code on this - I'd recommend to increase the multiplier slightly - I'm using 3 instead of 2 as I find that while this gets rid of most of the ugliness, there are some edge cases that would benefit from a little more "room" for the nozzle to lay down the one line infill. For example, the top walls of a benchy.

**Comment by igiannakas** [comment]
> Just noticed that BambuStudio has their own impl of the "Single wall on top surfaces" for Arachne. Not sure if it's better quality than us.

No it suffers from the same issue and the code is not as clean as orca. I’ve submitted a PR to resolve the same issue on the BL slicer.
