### ISSUE TITLE
[FR] Add start print time option in printer settings

### ISSUE THREAD

**Issue by meltiseugen** [SoftFever/OrcaSlicer#1714]
Add a simple input box where we can add a time (in seconds) that would be added to the total estimated time.

It is useful for having better time estimations when the printer takes like 5-10 min to heat up/ mesh the bed, etc. before actually starting to print

**Comment by DVSVIDEO** [comment]
And what would this be used for?  The clipper always prints the total print time and the actual time at the end of the print. If you know your printer just add 5-10 minutes (as many as you need)
In the end it will make Orca Slicer as miserably complicated as Cura, which is why I hate it.
Just print really nice....

**Comment by discip** [comment]
Duplicate of #904.
