### ISSUE TITLE
Strange wall behavior

### ISSUE THREAD

**Issue by DVSVIDEO** [SoftFever/OrcaSlicer#1715]
**Describe the bug**
Strange changes of direction/breaks in the wall in 1.6.4-beta2 version (see below, bottom photo)

**3mf File for This Bug**
[ShallowWaterDispencer.zip](https://github.com/SoftFever/OrcaSlicer/files/12269602/ShallowWaterDispencer.zip)

**To Reproduce**
Same project file. Normal slice procedure both versions. 0.3mm layer height, 4 wall perimeter
Only one wall on top layar is on

**Expected behavior**

**Screenshots**
1.6.4-beta
![1 6 4_beta](https://github.com/SoftFever/OrcaSlicer/assets/96373457/2727b89d-3aa4-4ae4-b5d0-7ea81adddfc3)
1.6.4-beta2
![1 6 4_beta2](https://github.com/SoftFever/OrcaSlicer/assets/96373457/5564f1e1-20ee-4ba9-9e8a-655e54eff182)
![1 6 4_beta2_2](https://github.com/SoftFever/OrcaSlicer/assets/96373457/4ddf51b5-f296-4370-a862-bd52180840a6)

**Printer model**
Micromake C1 -modified (core XZ)
**Desktop (please complete the following information):**
 - OS: Win10

**Comment by SoftFever** [comment]
This is caused by the the single wall on top.
Half of the area are qualified to apply single wall while other half doesn't ;)
I'll see if need to be fine tuned or allow user to change the threshold parameter

For now, as a workaround you can either turn off `single wall on top` for this model or change line width of inner walls to 0.6mm
![image](https://github.com/SoftFever/OrcaSlicer/assets/103989404/fc9c6185-32ee-47c0-b40a-23a447f1c04b)

**Comment by DVSVIDEO** [comment]
Okay. I printed it with a single wall off. Thanks for the reply.
I really like this slicer, it's much easier to use and does things the others don't.
Keep up the good work (just don't make it as complicated with all the settings as the Cura. Only know the basics, but know them well...)
