### ISSUE TITLE
export and import profiles on different computers

### ISSUE THREAD

**Issue by Jas0n913** [SoftFever/OrcaSlicer#1739]
Is it possible, to export config profiles and then import them on a different computer and still have them all available?

 I have a few profiles for different layers, materials and nozzles and I want to use them on a different computer as well.

**Comment by kylek29** [comment]
I believe you can export a lot of them using the UI (there are a few menu options to "Export" or "Import" certain configs). But if you want the backdoor way, you can go into the appdata and copy the profiles that way.

If using Windows, open File Explorer and type:
%appdata%
* This assumes you haven't redirected the profiles folder using the "-datadir" shortcut argument.

Locate the properly named folder (on my computer it's BambuStudio-SoftFever, but it might be different now, so also check OrcaSlicer). Inside that folder -> user -> ########### -> profiles are in filament/machine/process. There's also the "default" folder, which stores the local copies (defaults), you *can* put things in that folder, which is what I do because BambuLab has a tendency to overwrite my profiles on first sync.
