### ISSUE TITLE
Slicer thinks overhangs are bridges

### ISSUE THREAD

**Issue by inline6power** [SoftFever/OrcaSlicer#1749]
In the latest beta, if you have a speed set to say 100mm for bridges and also have on detect or slow down for overhangs, it will act as if the outside perimeter is a bridge. Instead of slowing down for overhangs it will speed up to what ever the bridge speed is

**Comment by gbyleveldt** [comment]
I have this exact issue at the moment, I even went so far as to exhaustively explain the issue on Orca Discord.

I believe the issue is prevalent when using Classic mode as opposed to Arachne (I have not tested this myself as I don't use Arachne).

This model works like it should, although it detects overhangs as normal outer wall. But it still slows down like it should

<img width="1198" alt="Screenshot 2023-08-09 at 14 16 01" src="https://github.com/SoftFever/OrcaSlicer/assets/69592072/c5c811c2-8829-48e8-a9f0-3a1a37d5acaf">

<img width="1202" alt="Screenshot 2023-08-09 at 14 13 33" src="https://github.com/SoftFever/OrcaSlicer/assets/69592072/f534cc7b-d911-4d46-a3ca-b8f300867a83">



Then, using the exact same project and settings, but replacing the model, it identifies overhangs like it should, but it uses the bridging speed on the overhangs, not the overhang speed

<img width="1198" alt="Screenshot 2023-08-09 at 14 19 06" src="https://github.com/SoftFever/OrcaSlicer/assets/69592072/4f37b2a2-4c18-4db1-ba67-2e1a68d2f021">

<img width="1200" alt="Screenshot 2023-08-09 at 14 19 29" src="https://github.com/SoftFever/OrcaSlicer/assets/69592072/84cc6c78-871c-4559-a449-61659c6989cc">

I've included the two projects for your reference

[Archive.zip](https://github.com/SoftFever/OrcaSlicer/files/12304554/Archive.zip)

**Comment by inline6power** [comment]
Sure hope they fix this. I really only use classic walls and run my bridges as 150ms but now have to run them slow in order to slow down for overhangs. This is the only thing that's bothering me on beta 2
