### ISSUE TITLE
[Bug] Fan speeds incorrect based on layer time and cooling settings

### ISSUE THREAD

**Issue by psiberfunk** [SoftFever/OrcaSlicer#1767]
**Describe the bug**
The slicer appears to have problems properly assigning fan speeds according to the rules set in the filament cooling tab.

**3mf File for This Bug**
See Attached:  
[FanSpeedIssue_OrcaSlicer_CaliCross_XY.zip](https://github.com/SoftFever/OrcaSlicer/files/12317919/FanSpeedIssue_OrcaSlicer_CaliCross_XY.zip)

**To Reproduce**
Slice the file, observe the fan speed, for example, on layer 16, which shows a fan speed on the whole layer of 53%, whereas the layer TIME on this layer is 32.8 seconds.  Accordingly, the fan speed **should be** 10%, and not 53% !

**Expected behavior**
Fan speed should respect the layer time rules in the filament profile settings instead of picking a seemingly random value for the layer.

**Screenshots**
![Screenshot 2023-08-09 094906](https://github.com/SoftFever/OrcaSlicer/assets/19777571/3271e4dd-d05f-47f4-b15f-201284e75673)
![Screenshot 2023-08-09 094923](https://github.com/SoftFever/OrcaSlicer/assets/19777571/cf5a098b-acd5-49e8-950e-16c609e3af30)
![Screenshot 2023-08-09 094936](https://github.com/SoftFever/OrcaSlicer/assets/19777571/c23e6652-d1f3-43e7-80dd-87938fde0ee7)

**Printer model**
Bambu X1C

**Desktop (please complete the following information):**
 - OS:Win64
 - 1.6.4 beta 2 , but verified problem also exists in 1.6.3 release.

**Comment by psiberfunk** [comment]
Addendum:  Please also see this similar but different (layer height =0.2 mm instead of 0.16 ) example where, on layer 19, despite the fan speed settings demanding a speed of 10, the slicer sets a speed of.. 80 ??     (layer time >>30 s!)

Project file attached.

![image](https://github.com/SoftFever/OrcaSlicer/assets/19777571/48c34f94-be24-4554-8b36-b77206413ff6)
[FanSpeedIssue_0.2Layerheight_OrcaSlicer_CaliCross_XY.zip](https://github.com/SoftFever/OrcaSlicer/files/12317941/FanSpeedIssue_0.2Layerheight_OrcaSlicer_CaliCross_XY.zip)

**Comment by SoftFever** [comment]
I took a quick look and also compared the behavior with PrusaSlicer. 
It appears to have the same behavior. This is likely not a bug. 
When tracing the code, I found that the layer time was around 12 seconds instead of the 32 second shown in the final UI for fan speed calculation. Without delving deeper, it's difficult to make a conclusive judgment. 
It's possible that this could be the original layer time before applying slowdown. 
Considering the priority and the fact that this feature is mature, having existed and been tested by many users for years, I'm inclined not to change it.

PrusaSlicer project(you need to use open project to open it)
[ps_fan.zip](https://github.com/SoftFever/OrcaSlicer/files/12320475/ps_fan.zip)

**Comment by psiberfunk** [comment]
Is the bug, instead then, that the layer time display is lying here ?  Perhaps that's actually what's wrong ?

I have another utterly bizarre example of fan speed mismatch to bring to the table where it applies it only to internal perimeters, but that seems like it may be a separate issue , and I will file it separately.

**Comment by psiberfunk** [comment]
More information here: https://github.com/bambulab/BambuStudio/issues/2260

Bambu looked at the code and determined that the layer times used for fan speed vs ACTUAL layer time are different.  The fan-speed is based off a crude estimation that does not account for accelerations, for example.  Of course this can make the fan speeds based off of pretty inaccurate layer times in certain situations, particularly with the higher speed printers we're dealing with these days.

**Comment by Knockout808** [comment]
i have this same issue with my P1S and it has made using orcaslicer impossible for ASA and ABS when doing multifilament prints. I have to switch to Bambuslicer for my multifilament prints as this bug is not present in it. It's so annoying becasue I love fuzzy skin and Orcaslicers newest fix to how walls are printed when using a model modifier to prevent fuzzy skin in certain areas.

**Comment by psiberfunk** [comment]
@SoftFever  can this be re-opened ? it seems to be still a valid glitch.
