### ISSUE TITLE
Disable blowing for internal bridges

### ISSUE THREAD

**Issue by gogsi1** [SoftFever/OrcaSlicer#1793]
**Is your feature request related to a problem? Please describe.**
The problem when printing abs and other plastics where strong blowing is not recommended

**Describe the solution you'd like**
Add functions like in superslicer. So that you can adjust or disable the airflow for internal bridges

**Comment by movinimage** [comment]
This! For a large flat object made of ABS/ASA or other high-warp materials, this is critical to avoiding failure. As it stands, I turn down the blower by hand while I sit by the printer! Otherwise the object pops of the build plate without fail.

Here is an example of something that fails every time unless blower is turned down...the object is 1/4" thick at the top of the first giant layer.

<img width="584" alt="Screenshot 2023-09-03 at 11 03 02 AM" src="https://github.com/SoftFever/OrcaSlicer/assets/13089904/198f31a0-9e04-494c-aac5-ab1f0eeceeb9">
