### ISSUE TITLE
Mouse Ears clearance error

### ISSUE THREAD

**Issue by kolchagov** [SoftFever/OrcaSlicer#1838]
**Describe the bug**
When using mouse ears brim with elephant foot compensation, the brim is not sticking to the object

**3mf File for This Bug**
not needed

**To Reproduce**
Enable elephant foot compensation for example 0.15 and enable "mouse ears" brim, set brim object gap to 0 (which have to be default instead 0.1 by the way)

**Expected behavior**
mouse ears brim should touch the print object

**Screenshots**
Elephant foot compensation on: https://ibb.co/7SqLmxM
compensation off: https://ibb.co/z2RL0kx

**Printer model**
any

**Desktop (please complete the following information):**
 - OS: MacOS Monterey

**Comment by Noisyfox** [comment]
That's exactly how "Elephant foot compensation" works.

**Comment by SoftFever** [comment]
@kolchagov 
Let me elaborate further:
When we set the elephant foot compensation to 0.15, the slicer will shrink or offset the first layer (of the object) by 0.15mm. This compensates for the extra expansion caused by an imperfect first layer's z-offset.

Brims, and their associated brim gaps, are generated based on the original object shape. Altering this could disrupt the actual print. Picture the red lines as the object boundaries after printing.
![Screenshot 2023-08-19 at 9 58 25 AM](https://github.com/SoftFever/OrcaSlicer/assets/103989404/c02ec950-1da2-47f9-8252-2e66b556fd7d)

**Comment by kolchagov** [comment]
Ok, I understand that, but still the clearance is too big. Even setting elephant compensation to 0 separates the mouse ears from the object. Classic brim works fine though.
here is a real photo: https://ibb.co/3ND6MsV

**Comment by SoftFever** [comment]
@kolchagov 

From the generated gcode, everything works as expected; it might be an inconsistent first layer issue.
Which is a more suitable topic for the community forum/discord.
