### ISSUE TITLE
Show estimated print time in the ruler like on prusa

### ISSUE THREAD

**Issue by cpasoft** [SoftFever/OrcaSlicer#2045]
It would be nice to port this feature to Orca...

![imagen](https://github.com/SoftFever/OrcaSlicer/assets/29692062/cd8ddbfb-deee-409a-be2e-f4373c3a92bf)
![imagen](https://github.com/SoftFever/OrcaSlicer/assets/29692062/7fbb6675-b64d-4445-929d-eb097ad835c3)

**Comment by discip** [comment]
## Second that!

Additionally, regarding inserting things into the model mid print:

It would be really convenient if there was a line for each 'pause' in the final **_'Total Estimate - Info Board'_** so that you know when to be ready to insert what ever you planned into the print.
Currently, estimating when each break will occur is a relatively laborious process.

**Comment by Eldenroot** [comment]
This is annoying, I miss this feature from PS.

@SoftFever

**Comment by niklasb22** [comment]
I will have a look at It

**Comment by cpasoft** [comment]
Great!

**Comment by discip** [comment]
@cpasoft
Was addressed in #2305.
Please don't forget to close. 😊

**Comment by cpasoft** [comment]
> @cpasoft Was addressed in #2305. Please don't forget to close. 😊

Great. Thank you so much :-)

Closing then...
