### ISSUE TITLE
The button and the text crawl out of the window when the interface language is different from English.

### ISSUE THREAD

**Issue by man55** [SoftFever/OrcaSlicer#2074]
### OrcaSlicer Version

1.7.0

### OS version

Windows 11

### Printer

Bambu X1C

### How to reproduce

Change language to ukrainian or rusian

### Actual results

The button and the text crawl out of the window The button and text extend beyond the window and become inaccessible.
<img width="486" alt="en" src="https://github.com/SoftFever/OrcaSlicer/assets/30772900/ba3b22d9-4cae-476f-85ee-d6b55f27b36a">
<img width="476" alt="ru" src="https://github.com/SoftFever/OrcaSlicer/assets/30772900/fba085aa-f08d-4a99-a83f-3326c4a6243c">
<img width="485" alt="ua" src="https://github.com/SoftFever/OrcaSlicer/assets/30772900/4c10b757-4850-48bf-a9e8-e9e8ec09758f">
This is how it should be (like in English)
<img width="486" alt="en" src="https://github.com/SoftFever/OrcaSlicer/assets/30772900/2387044a-b1f4-4e82-85e5-90fe2e35546c">

Changing the scale in Windows or the font size within reasonable limits does not solve the problem.

### Expected results

?

### Project file & Debug log uploads

no need any Project file

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by AndylgTom** [comment]
There are two ways to solve the problem:
1) Translation to reduce, wrote «Дозаправка» (все что длиннее уже проблема), which will improve the situation. The same goes for the buttons. But it's a crutch... But until the gui is fixed, apparently this is the only way (you can use https://disk.yandex.ru/d/T638qxqnsk4GyQ for now.  В след. обновлении перевода так будет пока). It looks like 
![image](https://github.com/SoftFever/OrcaSlicer/assets/20997012/200b7fd4-f220-43cd-9645-f9f371b752d6)


2) I would like the Gui to be fixed. So that as if the alignment of the text of this line (msgid "Auto Refill") was on the right edge, and the inscription itself stretched to the left.
And in general, there are plenty of such places, they don't think much about other languages.
