### ISSUE TITLE
Minimize/disable flush/starting purge

### ISSUE THREAD

**Issue by zubamse** [SoftFever/OrcaSlicer#2091]
**Is your feature request related to a problem? Please describe.**
There is much wasted plastic when starting a print, and if you dont care or printing the same colour it's not needed.

**Which printers will be beneficial to this feature**
Bambu printers

**Describe the solution you'd like**
it's more of an enhancement of the starting parameters, where i would like a tick box to enable or disable starting flush/pruge.

![image](https://github.com/SoftFever/OrcaSlicer/assets/142310503/9e4d8222-c6fe-4ae3-a689-af563713bdac)

**Describe alternatives you've considered**
Editing the starting gcode is possable, but im not smart enough to do that.

**Additional context**
There might a existing topic/ feature request of this, but i can't find it.

**Comment by kylek29** [comment]
In the meantime, here are some ideas for a work-around.

What part of the process are you referring to? I disabled the back right corner purge line, you just need to comment out a block of the printer start G-code (just note that you have to bring forward any Bambu Lab changes to that section).

To disable the back corner purge line, find this at the bottom (Printer Settings -> Machine G-Code -> Machine Start G-Code), and replace (or just comment them):

`;G1 E{retraction_length[initial_no_support_extruder]} F1800
;M109 S{nozzle_temperature_initial_layer[initial_no_support_extruder]}
;G0 X253 E6.4 F{outer_wall_volumetric_speed/(0.3*0.6)    * 60}
;G0 Y128 E6.4
;G0 X252.5
;G0 Y252.5 E6.4
;G0 X128 E6.4`

I think the little spiral circling bit is a function on the printer, likely called by the area right before `
;===== wipe nozzle ===============================` .. the problem with that, is it likely uses firmware specific commands to determine whether to run the procedure or not (you see this elsewhere with the other procedures) since those flags would be submitted after the slice action.


If they bring forward the PruserSlicer's custom variables, it's possible we maybe able to do this before the slice using some if statements.

**Comment by zubamse** [comment]
Yes i was thinking about the "poop" it makes when changing colour, but at the start of every print.
But you are saying that it might not be possibly to disable that?

**Comment by dkbay** [comment]
I'd honestly like this too.
Sometimes I forget to pick the right build plate in the slicer and the printer "flushes" twice in a row which is utterly unnecessary.

**Comment by jensim** [comment]
Plus one! 

Less poop!

**Comment by jensim** [comment]
I saw the kickstarter for IdeaFormer IR3 V2 (conveyerbelt printer), and it seems like a godsend for printfarming. But for us lowly hobbyists, I'll settle for the machines I have and being able to save a few grams on every print by skipping some poop breaks.
