### ISSUE TITLE
Speed specific Temperature

### ISSUE THREAD

**Issue by TheUnlimited64** [SoftFever/OrcaSlicer#2123]
**Is your feature request related to a problem? Please describe.**
I sometimes have trouble printing small overhangs in PLA, because it curls. My current fix it to print at a lower temperature, but that results in less speed for the Infill etc.

**Which printers will be beneficial to this feature**
Probably everone
**Describe the solution you'd like**
My suggestion would be, that the Temperature can be tweaked for the speed. For example layers with overhangs will be slower and get printed at lower temperature. But layers with only infill and no overhang would be printed faster with higher tempature (higher flow)

**Comment by kylek29** [comment]
This has been suggestion on the PrusaSlicer GitHub as well which gained some interest but never progressed. 

With the speed that many heater elements can heat up, it does make sense to be able to have a more dynamic approach to adjusting things.

Another example is with filaments that are highly susceptible to glossing at different speeds, especially if that particular section is really small. You sometimes need the higher temp to get the speed (knowing filament won't get that high as it's extruding so fast), but that higher speed causes a glossy appearance on shorter spans because it is getting to that temperature.
