### ISSUE TITLE
Support base overlaps causing fist layer collison

### ISSUE THREAD

**Issue by Edzi11** [SoftFever/OrcaSlicer#2178]
### OrcaSlicer Version

1.7.0

### OS version

Windows 11

### Printer

Bambu Lab X1C

### How to reproduce

1. load model
2. enable support
3. support first layer overlaps

### Actual results

first layer of supports overlap with each other causing collision. view attached image 
![overlap](https://github.com/SoftFever/OrcaSlicer/assets/123626106/e9b75308-63c9-4724-a803-40e985d526d6)
 

### Expected results

when generated the supports first layer chould merge together rather than collide with each other. almost seems like theres a raft being printed even though that isnt enabled. 

### Project file & Debug log uploads

[elder_wand project.zip](https://github.com/SoftFever/OrcaSlicer/files/12668148/elder_wand.project.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by ohmdelta** [comment]
this seems to still be in the latest 1.9.0 release (can also be duplicated in Linux image with close objects)

**Comment by Steak77** [comment]
Running 2.1.1 and the issue is still present:

![Image](https://github.com/user-attachments/assets/aa52dbc6-b565-455b-b23c-9d977515df30)

**Comment by shaileshaanand** [comment]
This bug is still present in version 2.3.0

No collision warnings are indicated upon slicing.

<img width="1436" height="897" alt="Image" src="https://github.com/user-attachments/assets/85de1848-1d22-455b-beac-5533f2519a27" />
<img width="1436" height="897" alt="Image" src="https://github.com/user-attachments/assets/05354ec1-daf5-4c57-96ea-cbfb3d4682e5" />
