### ISSUE TITLE
Device View: Save zoom facotr

### ISSUE THREAD

**Issue by dabohda** [SoftFever/OrcaSlicer#2285]
**Is your feature request related to a problem? Please describe.**
I just started using orca Slice and immediately loved the device view for my klipper printer. And i can even zoom in with ctrl+mousewheel. But after some time, at the latest when i restart orca, i have to set my preferred zoom factor again.

**Which printers will be beneficial to this feature**
Any web based device view.

**Describe the solution you'd like**
Add a visual zoom option like a Magnifier with the actual zoom factor and save the last used zoom factor for the selected printer or be able to set it in the printer settings.

**Comment by bordermultimedia** [comment]
I just osted the same issue and closed it when I found this, this was what I had written:

Is your feature request related to a problem? Please describe.
Every time I start Orcaslicer to one of my klipper printers running Fluidd or Mainsail I have to reduce the size by pressing Ctrl and using the mouse wheel, since the interface is too big for my laptop screen.

Which printers will be beneficial to this feature
All Klipper printers

Describe the solution you'd like
It would be nice if the internal browser could save the last used setting for that URL

Describe alternatives you've considered
As an alternative, nicer but maybe more complex, you could set the default zoom size of that particular URL interface within the printer integration setting, next to the "Device UI" field.
