### ISSUE TITLE
Slicing hangs, freezes if canceled

### ISSUE THREAD

**Issue by ZedOud** [SoftFever/OrcaSlicer#2326]
### OrcaSlicer Version

1.7.0

### OS version

macOS 14.0

### Printer

FLSun v400

### How to reproduce

I found a model for which the default profile plus `Extra perimeters on overhangs` causes slicing to not proceed past: "Slicing plate 1: Generating walls. 15%"

1. Default profile
2. Enable `Extra perimeters on overhangs`
3. Slice plate

### Actual results

It does not proceed past 15% as stated above, but the interface remains active. However, if you attempt to stop the slice the software will freeze, requiring a force quit. 

On the few printers I tested this occurs on the: 
FLSun v400
Tronxy X5SA 400

I tested on other printers with no problems on their default 0.2mm profiles:
Ankermake M5
Anycubic Chiron
Anycubic Kobra Max

### Expected results

This is an unexpected problem slicing a specific model on specific printers (using otherwise default profile).

### Project file & Debug log uploads

[logs.zip](https://github.com/SoftFever/OrcaSlicer/files/12811102/logs.zip)
[crashing Kobayashi cube project.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/12811110/crashing.Kobayashi.cube.project.3mf.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by pentolope** [comment]
@SoftFever I have a similar issue in OrcaSlicer 2.1.1. However, it is not related to "Extra perimeters on overhangs". 

**OrcaSlicer Version**
2.1.1

**OS version**
Windows 10 (Build 19045)

**Printer**
Creality K1C

**How to reproduce**
I found a model for which the default profile causes slicing to not proceed past: "Slicing plate 1: Generating walls. 15%"

1. Default profile
2. Slice plate
3. It does not proceed past 15% as stated above, but the interface remains active. However, if you attempt to stop the slice the software will freeze, requiring an "End Task" in Task Manager.

**Project file & Debug log uploads**
[output_file_00196.3mf.zip](https://github.com/user-attachments/files/16679766/output_file_00196.3mf.zip)

The log files contain three relevant pieces of information: 
[error]	2024-08-20 11:16:59.384345[Thread 0x00002304]:Slic3r::GUI::PartPlate::calc_exclude_triangles:Unable to create exclude triangles
[error]	2024-08-20 11:18:12.809911[Thread 0x00008ab4]:Reversing even wall line causes it to be printed CCW instead of CW!
[error]	2024-08-20 11:20:46.603194[Thread 0x0000a064]:Slic3r::BackgroundSlicingProcess::call_process:got cancelled exception

The first error appears even when slicing succeeds, but the second may only occur when slicing hangs.

**Other information:**
If the setting "Other->Special Mode->Slicing Mode" is changed from "Regular" to "Close Holes" then the slicing succeeds. I am not sure what other settings will cause slicing to succeed.

This stl was generated by a piece of software that I wrote. Although the stl is complex, I am reasonably confident that the stl is valid and does not contain any holes. I have been able to slice the other 254 files that this software generated. If you find that the stl is invalid, please let me know.
