### ISSUE TITLE
Tree support overlaps model with variable layer height 

### ISSUE THREAD

**Issue by StanislavChumarin** [SoftFever/OrcaSlicer#2327]
### OrcaSlicer Version

1.7.0

### OS version

macOS 13.6

### Printer

Creality Ender-3 S1 Pro 0.4 nozzle

### How to reproduce

1. Load curvy model
2. Enable variable layer height
3. Enable Support. Type: tree (auto)
4. Slice plate
5. Observe interaction of support and object

### Actual results

Support layers and object layers are overlapped or supports empty space (way below expected level)
![Screenshot 2023-10-05 at 11 33 01](https://github.com/SoftFever/OrcaSlicer/assets/1260322/8e7e0996-02e8-4fbc-9ebd-987e6f310d50)
![Screenshot 2023-10-05 at 11 33 27](https://github.com/SoftFever/OrcaSlicer/assets/1260322/5834fb02-876e-4f33-b76c-b67a183b1fc0)

### Expected results

Support structure must not overlap with object and support model

### Project file & Debug log uploads

[wrong_tree_support.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/12816766/wrong_tree_support.3mf.zip)
[debug_Thu_Oct_05_11_37_49_32065.log.0.zip](https://github.com/SoftFever/OrcaSlicer/files/12816767/debug_Thu_Oct_05_11_37_49_32065.log.0.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by Ocraftyone** [comment]
The latest 1.8 beta now displays an error stating that variable layer height is not compatible with organic supports.

**Comment by cramsvik** [comment]
Loogs to me like layer height for the tree supports is static (at lowest? at slicer setting?) while some of they layers are way higher. This causes the supports to be way too short to reach where they are supposed to be, and it also caused the supports to merge into the model at some places, probably because the "scaled down" curve of the supports don't match the curve on the model.

<img width="630" alt="Screenshot 2023-10-12 at 14 59 24" src="https://github.com/SoftFever/OrcaSlicer/assets/7917520/1807ba47-f7a6-4d58-a85c-9263225ba547">

<img width="677" alt="Screenshot 2023-10-12 at 14 59 55" src="https://github.com/SoftFever/OrcaSlicer/assets/7917520/84748961-00fc-4a95-a3f6-ae00025a0460">

<img width="816" alt="Screenshot 2023-10-12 at 15 04 45" src="https://github.com/SoftFever/OrcaSlicer/assets/7917520/5e8e0f34-d6b1-46bd-a568-ca8dac3dbbe2">
<img width="897" alt="Screenshot 2023-10-12 at 15 03 06" src="https://github.com/SoftFever/OrcaSlicer/assets/7917520/a6b4ba4a-288d-4014-b9e4-e3c0bbb9b567">

**Comment by arittner** [comment]
> Loogs to me like layer height for the tree supports is static (at lowest? at slicer setting?) while some of they layers are way higher. 

Yeah, saw also the same bug. I tried to add tree support for very tall components and failed with variable layer height:


![Screenshot 2023-10-21 085831](https://github.com/SoftFever/OrcaSlicer/assets/5605065/35fb65ca-bce3-44be-9ae2-e070211c5c03)

The component in front is with variable layer height and adaptive calculation. The component behind with static layer heigth.

**Comment by evilDave** [comment]
I have just struck this issue also.

Supports generated with variable layer height and independent support layer height both selected intersect the model. Some support parts also printed in space (even with independent support layer height off)

I noticed this with a fairly complex model. I have provided the 3mf file without the model added, the model that I was using is this one: https://cults3d.com/en/3d-model/art/triceratops-skull. Notice collisions at layer 565 (and just before) for example (there are others), and support material in free space on layer 651

Collision:
<img width="885" alt="Screenshot 2024-08-29 at 16 15 06" src="https://github.com/user-attachments/assets/0a0ddf38-f478-4410-a44a-b07e958a1d18">

Odd support material:
<img width="996" alt="Screenshot 2024-08-29 at 16 14 24" src="https://github.com/user-attachments/assets/0999b877-5734-45cd-a94f-1d7c5648e6fb">

Without independent support layer height:
<img width="1011" alt="Screenshot 2024-08-29 at 16 24 28" src="https://github.com/user-attachments/assets/860019b9-ae7c-4e28-b527-cedae828dd02">

[tree_support_issue.3mf.zip](https://github.com/user-attachments/files/16793775/tree_support_issue.3mf.zip)
