### ISSUE TITLE
Smart Auto Upload and Start Print

### ISSUE THREAD

**Issue by alfondehesa** [SoftFever/OrcaSlicer#2367]
**Is your feature request related to a problem? Please describe.**
Currently, OrcaSlicer uploads gcode directly to octoprint. This workflow could be much more streamlined.

**Which printers will be beneficial to this feature**
All printers with octoprint as the network interface.

**Describe the solution you'd like**
OrcaSlicer should upload GCODE to Octoprint, wait until the printer turns on and is connected (or if not, turn it on), wait for GCODE analysis to complete, and then start the print.

**Describe alternatives you've considered**
[This plugin for Cura](https://github.com/fieldOfView/Cura-OctoPrintPlugin) performs this specific workflow.

**Additional context**
None.

**Comment by Ocraftyone** [comment]
If you are using klipper, Moonraker has some powerful power settings. You can specify that any time a file is added to the queue, it turns on the printer, waits to connect to the printer, then starts the job. https://moonraker.readthedocs.io/en/latest/configuration/#power

**Comment by evilDave** [comment]
It would be nice to see something like this feature make it possible to use "upload and print" with post processing plugins active on octoprint.

E.g. I have ArcWelder plugin processing incoming files, and "upload and print" has no way to wait for the processing to be complete: the original file gets printed, OR the file cannot be overwritten because it is already printing.

Something like detecting the processing complete and triggering the print of the same or updated file, or at the very least specify a delay between upload and print.

**Comment by tom-321** [comment]
I usually have my printer (with Klipper+Mainsail) turned off, so it would be great if I could set it to try uploading several times for a period of time until I walk over to the printer and turn it on.

Right now, I still have to walk back and press upload, which is really annoying.
