### ISSUE TITLE
Port automatic support painting from PS

### ISSUE THREAD

**Issue by Eldenroot** [SoftFever/OrcaSlicer#2428]
**Is your feature request related to a problem? Please describe.**
Missing seam painting options for detailed customization.

**Which printers will be beneficial to this feature**
All

**Describe the solution you'd like**
Add more options for seam painting like PS has. Could be available via expert mode?

**Describe alternatives you've considered**

**Additional context**
![image](https://github.com/SoftFever/OrcaSlicer/assets/778890/925e3f59-d433-4b7e-a488-3cc52611b718)

**Comment by Eldenroot** [comment]
@Noisyfox - any plans to backport this from Prusa?

**Comment by Noisyfox** [comment]
What you show in screenshot is the support painting, not seam painting.
![image](https://github.com/SoftFever/OrcaSlicer/assets/1537155/3a5d7081-421d-4c9d-9c66-05806e60d0fa)
Orca and PS have identical seam painting options (with slightly different wording).

![image](https://github.com/SoftFever/OrcaSlicer/assets/1537155/e56febd0-891c-4e6e-8945-45442259d2e7)
And for support painting the only thing missing from Orca is the Automatic painting, which I've attempted to add a long time ago but gave up due to how different the codebase were at that time. Might give it another shot since Orca's core codebase is much much closer to PS now.

**Comment by Eldenroot** [comment]
Srry, my mistake - the screenshot is not the correct one.

You are right. 

"Automatic painting of supports will be nice :)

**Comment by Phardbean** [comment]
This is exciting. Cleaning up the supports for minis to avoid nightmares is sooooo easy with this tool. I need it so badly.

**Comment by Eldenroot** [comment]
Yes, exactly :)

**Comment by Noisyfox** [comment]
I just did another attempt (https://github.com/Noisyfox/OrcaSlicer/tree/dev/auto-support and https://github.com/Noisyfox/OrcaSlicer/tree/dev/auto-support-2) a few days ago, and it turned out to again, more difficult than I expected.

**Comment by Phardbean** [comment]
You need to recruit help.🤓 wish I was capable.

**Comment by Eldenroot** [comment]
> I just did another attempt (https://github.com/Noisyfox/OrcaSlicer/tree/dev/auto-support and https://github.com/Noisyfox/OrcaSlicer/tree/dev/auto-support-2) a few days ago, and it turned out to again, more difficult than I expected.

Keep going, you can do this ;)

Fingers crossed!

**Comment by Eldenroot** [comment]
Staleness

**Comment by eVenom** [comment]
is this coming down the line?
