### ISSUE TITLE
Issue with the new camera update

### ISSUE THREAD

**Issue by Noisyfox** [SoftFever/OrcaSlicer#2472]
1.8.0-dev:
Caused by 388b48377434a6ee1a9ed8f6329c07a18d1a2157 

![动画](https://github.com/SoftFever/OrcaSlicer/assets/1537155/4dd1793d-11cb-4798-95d0-583b66b2a579)

1. Make a tall model, then scale it up until it's too big that the plate is tilting due to the scaling.
2. Then switch to preview tab
3. The 3d view camera rotation is totally messed up

**Comment by SoftFever** [comment]
I will take a look

**Comment by discip** [comment]
Good evening everyone.
I'm experiencing this weird behavior quite for a while now.

@Noisyfox
Could you please try if this behavior is also caused by zooming in and out on any e.g. corner of your build plate **(zoom to mouse position enabled)**?
This is enough to trigger it for me.

If you than press **`Ctrl+0`** everything is back to normal.

**Comment by discip** [comment]
Good evening everyone.
I'm experiencing this weird behavior quite for a while now.

@Noisyfox
Could you please try if this behavior is also caused by zooming in and out on any e.g. corner of your build plate **(zoom to mouse position enabled)**?
This is enough to trigger it for me and #2473 does unfortunately not solve it. 🤷🏻‍♂️

If you than press **`Ctrl+0`** everything is back to normal.

**Comment by discip** [comment]
Good evening everyone.
I'm experiencing this weird behavior quite for a while now.

@Noisyfox
Could you please try if this behavior is also caused by zooming in and out on any e.g. corner of your build plate **(zoom to mouse position enabled)**?
This is enough to trigger it for me and #2473 unfortunately doesn't solve it. 🤷🏻‍♂️

If you than press **`Ctrl+0`** everything is back to normal.

**Comment by Noisyfox** [comment]
> Good evening everyone. I'm experiencing this weird behavior quite for a while now.
> 
> @Noisyfox Could you please try if this behavior is also caused by zooming in and out on any e.g. corner of your build plate **(zoom to mouse position enabled)**? This is enough to trigger it for me and #2473 unfortunately doesn't solve it. 🤷🏻‍♂️
> 
> If you than press **`Ctrl+0`** everything is back to normal.

I can trigger the issue with your method with the master build, and with the https://github.com/SoftFever/OrcaSlicer/pull/2473 I could no longer reproduce it. The PR contains 2 commits, did you test with both commits?

**Comment by discip** [comment]
@Noisyfox
Ah, yes you are right!
That fixed it for me!
Tried this to see if that would solve the weird behavior prior to the #2473!

Thanks!
kind regards
