### ISSUE TITLE
X- Y- hole compensation 

### ISSUE THREAD

**Issue by BahamutWolf** [SoftFever/OrcaSlicer#2770]
I carried out the Orca tolerance test and set an X- Y_ hole compensation of 0.3. However, the problem with the hole compensation is that it does not fully compensate for holes. I have noticed an offset in 2 of my projects that I have designed with Fusion 360 that is caused by the compensation. You could solve the problem by using the X-Y contour compensation, but then the workpiece is no longer dimensionally accurate.

![Box 2](https://github.com/SoftFever/OrcaSlicer/assets/121379812/8bcd1114-14eb-498e-9df0-79622ad35c33)
![Box](https://github.com/SoftFever/OrcaSlicer/assets/121379812/b3d51811-753c-4cd9-9fb8-291c0724d0a8)
![Hülse 2](https://github.com/SoftFever/OrcaSlicer/assets/121379812/afcea1d5-bb98-4996-a2cc-7a18e4b74aaf)
![Hülse](https://github.com/SoftFever/OrcaSlicer/assets/121379812/9af5aa18-7265-482c-8890-f8274bea3b92)

**Comment by SoftFever** [comment]
It is because the hole compensation will stop at the non-hole area as the picture demonstrated.
We don't have a perfect solution for such cases, the only way I can think of is bringing the model back to CAD software and adjust the tolerance.

![image](https://github.com/SoftFever/OrcaSlicer/assets/103989404/6f6261cf-2969-41df-83eb-eee29815ca3e)

**Comment by BahamutWolf** [comment]
I understand. I thought that was a bug. I measured the outer diameter of the sleeve and it is 0.3mm too wide, so the hole should fit due to the compensation of 0.3 and contour compensation at -0.3. This step is then gone in any case. Thank you very much.
