### ISSUE TITLE
Surface pattern is being ignored

### ISSUE THREAD

**Issue by HakunMatat4** [SoftFever/OrcaSlicer#2892]
### OrcaSlicer Version

1.8.0 official

### OS version

Linux Mint Cinnamon

### Printer

Voron Trident

### How to reproduce

- Set bottom or top surface to Monotonic Lines
- Print it to have Monotonic pattern instead

This happens with any print.

### Actual results

This is Monotonic Line pattern

![20231126_181402](https://github.com/SoftFever/OrcaSlicer/assets/35049512/ab2721fe-8e4e-4339-b6db-ad62581fde26)

Well, this isn't Monotonic Line or I am seeing things haha

![PXL_20231126_083723473](https://github.com/SoftFever/OrcaSlicer/assets/35049512/969c952e-a971-4f16-b826-b7c3c6e98d97)

Monotonic instead of Monotonic Line
![PXL_20231126_040545326~3](https://github.com/SoftFever/OrcaSlicer/assets/35049512/fcd97de6-9de0-44f2-8fbd-9e83c1b5bf7d)

### Expected results

Errrrrr, to have Monotonic Line instead of Monotonic would be nice haha

### Project file & Debug log uploads

[Orca_debug.log](https://github.com/SoftFever/OrcaSlicer/files/13466294/Orca_debug.log)
[[a]_rear_half_g2.stl.zip](https://github.com/SoftFever/OrcaSlicer/files/13466297/a._rear_half_g2.stl.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by igiannakas** [comment]
Looks fine to me

Top:
![image](https://github.com/SoftFever/OrcaSlicer/assets/59056762/003c426f-fd55-4645-836a-928699a29852)

Bottom:
![image](https://github.com/SoftFever/OrcaSlicer/assets/59056762/a48f75ff-ec41-42c3-8af9-0bdac3bd05dc)

Infill:
![image](https://github.com/SoftFever/OrcaSlicer/assets/59056762/d1abda85-9b65-4927-9392-0c3a0b485f26)

Infill 2:
![image](https://github.com/SoftFever/OrcaSlicer/assets/59056762/53560119-61c9-443c-a082-287212b71154)

Project file:
[[a]_rear_half_g2.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/13466856/a._rear_half_g2.3mf.zip)

**Comment by Noisyfox** [comment]
Yeah I noticed that the monotonic pattern doesn't really work as intended, the extrusion direction is still changing. The only difference between monotonic and monotonic lines is the lines are connected or not.

**Comment by HakunMatat4** [comment]
> Looks fine to me
> 

The slicer looks fine indeed but it prints Monotonic instead of Monotonic Line.

Those prints above, Orca totally ignored the surface pattern like it was never there.

So it either I'm doing something very wrong of this is one more Linux bug like the gcode file Orca could never load on Linux for releases after releases, and yet worked fine everywhere else.

I've checked the option over and over, all my printer have Monotonic pattern.

**Comment by igiannakas** [comment]
Could you post your project file pls? Or even better the produced gcode file? Can check it in a gcode viewer.

**Comment by Noisyfox** [comment]
The only difference between monotonic & monotonic line is whether the lines are connected. I guess this could again be a retracting problem or something similar that affect the disconnecting between lines.

**Comment by igiannakas** [comment]
![IMG_2659](https://github.com/SoftFever/OrcaSlicer/assets/59056762/69f4ac2b-c817-4bde-9529-11329a9a850d)
![IMG_2660](https://github.com/SoftFever/OrcaSlicer/assets/59056762/54785b64-7472-448c-b218-227299df7a91)

I’m trying to see it in my models but I can’t. Please post the project file and gcode output to investigate when you can.

**Comment by igiannakas** [comment]
Ok may be going somewhere

Set Travel Distance threshold to 0 -> this should cause retractions to happen at every travel move
![image](https://github.com/SoftFever/OrcaSlicer/assets/59056762/15330e04-554f-460f-ac5d-e3d15a017252)

However retractions are not happening:
![image](https://github.com/SoftFever/OrcaSlicer/assets/59056762/5685396e-0a92-450f-9c95-11a4c4507267)

**Comment by igiannakas** [comment]
This may cause the extruded line to appear like monotonic as there is ooze during the travel move before starting to print the next line.

**Comment by igiannakas** [comment]
![image](https://github.com/SoftFever/OrcaSlicer/assets/59056762/5ff41081-5fb1-4187-9aac-3112c5c69d55)

It does appear to retract when there is a travel move to another area but not when moving to the next line.

**Comment by Noisyfox** [comment]
Have you compared with PS? I tried some test model on PS and it also doesn't retract at every lines.

**Comment by igiannakas** [comment]
> Have you compared with PS? I tried some test model on PS and it also doesn't retract at every lines.

Yeap - PS does retract on every move. Orca used to as well as I remember using that to try and get better surface quality but was unnecessary in the end.

![image](https://github.com/SoftFever/OrcaSlicer/assets/59056762/62dda5a0-01f4-484b-8931-469687358827)

**Comment by igiannakas** [comment]
Same issue (?) is also present on Bambu Studio:
![image](https://github.com/SoftFever/OrcaSlicer/assets/59056762/ff1567ba-1b7c-4d76-9716-87de4b7c3e16)

**Comment by HakunMatat4** [comment]
@igiannakas my bad, I thought I did that but sent the STL file instead, no comments.

[monotonic.zip](https://github.com/SoftFever/OrcaSlicer/files/13468174/monotonic.zip)

**Comment by HakunMatat4** [comment]
Sorry, haven't had coffee yet, you also asked for the gcode file.

[[a]_rear_half_g2_0.2mm_ASA_TIME_11g.gcode.zip](https://github.com/SoftFever/OrcaSlicer/files/13468196/a._rear_half_g2_0.2mm_ASA_TIME_11g.gcode.zip)

**Comment by HakunMatat4** [comment]
Orca will show you that everything is right but something is not correct and the printer is printing Monotonic instead.

**Comment by HakunMatat4** [comment]
Could that be the reason??
But again, you checked and retraction does no happen, perhaps left over from RC2.
You should have both the project and the gcode now.
Thanks a lot guys.

![image](https://github.com/SoftFever/OrcaSlicer/assets/35049512/d22a248f-1f62-4024-9afe-3d08ea1794c3)

**Comment by igiannakas** [comment]
> Sorry, haven't had coffee yet, you also asked for the gcode file.
> 
> [[a]_rear_half_g2_0.2mm_ASA_TIME_11g.gcode.zip](https://github.com/SoftFever/OrcaSlicer/files/13468196/a._rear_half_g2_0.2mm_ASA_TIME_11g.gcode.zip)

So Gcode is fine - it shows lines instead of monotonic infill - see below:
![image](https://github.com/SoftFever/OrcaSlicer/assets/59056762/233d4683-c1df-496a-aa78-1362bf8fd645)

![image](https://github.com/SoftFever/OrcaSlicer/assets/59056762/8d5731db-8549-460a-86bf-d59675fa7b03)


Seems like a different issue to me. Probably you're getting a bit of ooze at the end of a move that spills over during the small travel move to start the next line and that causes it to appear like monotonic. 

Retraction shouldn't be necessary for this type of pattern, so the issue identified shouldn't be the cause for what you see. Retracting at every line in monotonic lines infill will extend your print by a considerable amount, especially if you also have z hop enabled, so in general it is not recommended to retract at the end of every line for this type of infill.

However this can be **potentially** caused by incorrect PA settings as the extruder doesn't release the pressure fast enough when slowing down near the end of the line causing it to print less crisp ends. This is just speculation on my side 

Finally you will see infill like the below:

![image](https://github.com/SoftFever/OrcaSlicer/assets/59056762/d76783f0-9750-43fd-85ef-bd1e4ec21d63)

This is from the detect narrow infill algorithm. It converts small infill movements to concentric and / or monotonic in small regions to speed up printing. You can disable that feature if you want under the strength tab, but again this should not be necessary as it will significantly extend the print time for little/no benefit as the areas are hidden by the top surface that is always monotonic lines.

The fix on retraction when ending a monotonic line infill with travel distance threshold set to 0 is still needed; more from a consistency point of view rather than a usefulness point of view, but if I were you I'd look more into PA and Square corner velocity as your specific causes for this.

**Comment by HakunMatat4** [comment]
@igiannakas there's no way on Earth this is oozing. You can clearly see a perfect Monotonic pattern used instead of Monotonic Line. 
There no attempt to retract at all even so OrcaSlicer's legend shows it happening.
Oozing is very fine flow like a string and wouldn't be this uniform.

Indeed, the slicer also shows Line the the printed model shows otherwise.
Unless Klipper has a new feature setting pattern on its own. 

I'll try to print a test print with a different pattern like a cylinder with eccentric pattern.

 ![285638739-fcd97de6-9de0-44f2-8fbd-9e83c1b5bf7d.jpg](https://github.com/SoftFever/OrcaSlicer/assets/35049512/df244c36-dd3c-4f16-8918-e23bab3fb3a7)

**Comment by igiannakas** [comment]
It is indeed strange - however the Gcode doesnt show anything like this which makes it even more strange. Maybe worth trying clearing your print cache on Klipper and all stored files on Klipper just in case it's using a cached g-code file when you're printing.

**Comment by HakunMatat4** [comment]
@igiannakas , I have printed a few things and boy, it just keeps getting weirder.
Some prints does show the Monotonic Line patter while others shows it as Monotonic.
Even a cube a printed with Monotonic now shows the top as Monotonic Line.
Now at least, I can see some prints with Line pattern.

I cannot narrow down wtf is going on lmao and yes I changed all 3 patterns, bottom, top and infill.
I am closing this ticket until I can easily replicate the problem.
