### ISSUE TITLE
Outlines are not closed - Gaps between the sliced part

### ISSUE THREAD

**Issue by Rockevzel** [SoftFever/OrcaSlicer#2897]
I just added Files to the Slicer and sliced it. 
I cant find the issue. See picture below. The Lines should be closed

I didn't start the print yet. Maybe it's just a display error? 

![image](https://github.com/SoftFever/OrcaSlicer/assets/36402948/6ba3b9f1-6422-4a68-829f-72c03e27e542)

**Comment by igiannakas** [comment]
could you post the project file please?

**Comment by DVSVIDEO** [comment]
This is not a forum, but a bug reporting section.
If you yourself don't know whether it's a mistake or not, why are you adding to the number of mistakes?
This is something for the developers to look over and generates unnecessary work.
What you can do:
Print it and find out if it is a display error or not.
You check your settings, because maybe the seam settings are out of order.
You try the same project with an earlier version.
After that, you open an error ticket after careful consideration if it is really the fault of the slicer.
