### ISSUE TITLE
Mainsail displays wrong slicer name

### ISSUE THREAD

**Issue by Ibot-11** [SoftFever/OrcaSlicer#295]
When using Mainsail the table column for the slicer shows Superslicer.
Also a new name for this fork would be really nice.To say “Bambustudio SoftFever Fork” every time anyone asks you what slicer you are using is a bit annoying.
This fork already has so much more features than Bambstudio, that it really deserves a own name.
![image](https://user-images.githubusercontent.com/84148069/217815597-184d50c9-ccd9-40f3-a612-9bed978a884d.png)

**Comment by hliebscher** [comment]
this is not a bug!  
hack-fix: write fake slicer info here so that Moonraker will extract thumbs.

**Comment by SoftFever** [comment]
It's a temporary solution.
Moonraker can now recognize this slicer properly
I had a PR that had already merged into Moonraker mainstream a few months back.

The only thing left is to submit a PR to [`object canceling`](https://github.com/kageurufu/preprocess_cancellation) post-processing so that it recognizes this slicer.
I properly will implement preprocess in the slicer directly though.
