### ISSUE TITLE
Hitting organic support with nozzle in travel movements

### ISSUE THREAD

**Issue by Santars2022** [SoftFever/OrcaSlicer#2976]
### OrcaSlicer Version

All versions

### OS version

Windows 10

### Printer

Any printer

### How to reproduce

It depends on printed model

### Actual results

Screenshot in attachment

![image](https://github.com/SoftFever/OrcaSlicer/assets/110886710/e7f35e70-9445-453e-8bd1-474b1ee852f0)

### Expected results

Add: setting for avoid support when travelling or add z-hop only on supports

### Project file & Debug log uploads

![image](https://github.com/SoftFever/OrcaSlicer/assets/110886710/fd7df8f3-d3c3-43a6-a8f4-0cea2385c6f9)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Santars2022** [comment]
Hello! This is well known problem, but nobody is fixing it. Only Cura slicer programmers had fixed this issue. From now on i'm on cura slicer intil issue is fixed.
If you search on google this problem, you will find a lot of acticles about prusa slicer, there is the same issue.
As you see on the picture above, organic support is hit by nozzle even when travelled from tree to tree over already printed tree.

**Comment by Santars2022** [comment]
It's very sad that orca slicer programmers still didn't fix it

**Comment by gaaat98** [comment]
I am affected too! Several small and detailed prints fail when slicing with Orca but not with Cura because the nozzle knocks off supports or other printed parts! Z-Hop is sometimes a solution but introduces a lot of stringing, while "avoid crossing walls" doesn't seem to be working and does not apply to supports...
Avoid printed parts and avoid supports when printing are basically the only options I miss from Cura... I would really like to see them implemented in Orca (and I guess many other users too)!

**Comment by gaaat98** [comment]
#3254 presents a similar problem; path planning should be improved by introducing Cura settings such as combing and avoid printed parts/supports when travelling. I would really like to help but I don't know where to start...
