### ISSUE TITLE
XY-Compensation leads to artifacts for horizontal holes

### ISSUE THREAD

**Issue by Bumblebiber** [SoftFever/OrcaSlicer#3003]
### OrcaSlicer Version

1.8.1

### OS version

Win 11

### Printer

BambuLab X1E

### How to reproduce

By setting xy-hole compensation I'd like to make my vertical holes bigger. I think this works. But as an unwanted side effect, the walls arount horizontal holes become wider by  the same value.

### Actual results

![image](https://github.com/SoftFever/OrcaSlicer/assets/78353703/65e19be7-4cbb-464f-819c-5a9f69e418d0)

### Expected results

![image](https://github.com/SoftFever/OrcaSlicer/assets/78353703/073daf15-cf9e-483b-89cc-1c60cd3013c5)

### Project file & Debug log uploads

[frame.zip](https://github.com/SoftFever/OrcaSlicer/files/13558936/frame.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by LupusTheCanine** [comment]
IMHO this could be simplified by doing three things
1) Apply contour expansion to all edges
2) Apply hole expansion to holes after step 1.
3) Allow painted on horizontal expansion.

Steps 1 and 2 would make calibration easier because if the printer undersizes lines by lets say 0.03mm holes will be expanded by 0.03mm too so it makes sense to apply compensation to all edges.
Then hole compensation can be used to adjust hole dimensions, also add maximum hole size to limit the scope.
