### ISSUE TITLE
Z Hop settings do not work if the Z-offset is set too low

### ISSUE THREAD

**Issue by Iridium-IO** [SoftFever/OrcaSlicer#3108]
### OrcaSlicer Version

1.8.1

### OS version

Windows 11

### Printer

Ender 3 S1

### How to reproduce

1. In the `Printer settings` menu, set the Z-offset to a value that is a negative value lower than the total height of the model (for example if the model is 3mm high, set the Z-offset to -4mm). 
2. Change any of the Z-hop parameters, and check the resulting sliced preview and Gcode

### Actual results

Review GCode while panning through layers, there will be no Z Hop at any retractions despite this being set; no vertical travel paths indicating this is occurring either.
This applies to _any_ layer that lower than `LAYER_HEIGHT + Z_OFFSET`; if your Z-offset if -1mm, then you'll see normal Z-hops on all layers above 1mm. All layers below 1mm (the first 5 layers if your layer height is 0.2mm) will have their Z-hops disappear entirely. 

![_FailedZHop4](https://github.com/SoftFever/OrcaSlicer/assets/1491536/216af1ef-2206-4e96-9f08-c0b0b32a79f7)

If you set the Z-offset to anything higher (i.e if the model is 3mm high and you set the Z offset to -2mm), you will be able to see the travel moves again. However, note that they are glitched and show the spiral move (or slope move/normal hop move) with an incorrect offset barely above the build plate. Note that in the GCode here you can actually see the G3 move as opposed to the example above. 

![_FailedZHop3](https://github.com/SoftFever/OrcaSlicer/assets/1491536/61f3166d-29c0-4d16-b25d-e27a1f751cb7)

This appears to be a bug in how the Z-hop is calculated, and is incorrectly using the Z-offset to calculate a relative Z-move. When the Z-offset is too low (i.e. it will try to slice a move below the build plate), the code seems to simply delete the Z-move entirely. 

### Expected results

The slicer should not use the Z-offset as an absolute subtraction when calculating the Z-hop height. 
It seems to be a case where the slicer determines the Z-hop height by using something like `Z=CURRENT_HEIGHT + Z_OFFSET + Z_HOP_HEIGHT` and if this value ends up <0, it discards it entirely. 
Note that the way OrcaSlicer uses the Z-Offset value in the first place is to apply it to every Z move individually, rather than using e.g. `M851` to set it globally at the start of the print. So if you have a Z offset of -3.0mm, the first layer's Gcode will start with a `G1 Z-4.00` and every subsequent layer will move this up by the layer height. 

It would seem that the slicer allows negative absolute Z moves in layer moves, but errors out when Z-hop moves end up being negative. 

### Temporary Bypass
You can get around this bug by setting the Z-offset to `0.00` in the printer settings, and instead add a `SET_GCODE_OFFSET Z=` line to your start G-code (that's for Klipper, Marlin should use the `M851` GCode). 

### Project file & Debug log uploads

[FailedZHop.zip](https://github.com/SoftFever/OrcaSlicer/files/13662800/FailedZHop.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by ImminentFate** [comment]
Updated information:
There appears to be a bug that manifests at some point _after_ you save a custom printer profile; leaving it at the default profile (e.g. Creality Ender-3 S1 0.4 nozzle) will allow z hop and retraction settings to work.  Once the bug has occurred, even if you attempt to set all custom values in your profile to match the default, it **still won't work**. You have to make modifications from the stock profile and then overwrite the broken one.  I should have done a diff against the modified configuration file and the stock one to see what actually changed, but unfortunately I didn't before overwriting the broken profile.

**Comment by Novichek-13** [comment]
The problem is still relevant, I thought that I had something wrong with the position of the z-axis beam or the bed. The nozzle was constantly hitting the model and the supports. Having discovered this topic, I checked the ways of moving the head in ORCA and found that the code for lifting the nozzle does not work when moving. Going into PrusaSlicer 2.7.4 and slicing the model there, I found that everything works as it should. Will there be a solution to this problem in the coming releases? My printer is Anycubic Kobra 2 Pro

**Comment by XenoChron** [comment]
This is still a bug/issue as of Marc 23, 2025. I've been having an issue with this with a negative offset and not able to get z hop working on a first layer. Once I removed the offset in Orca I can see the z hop being generated in the Gcode in the slicer.  Is this NOT a bug? It doesn't seem like having the z offset break z hop would be an intentional.

**Comment by Rico-origin** [comment]
I also have this problem! I probably destroyed my hot end becouse of this and only realised now, when I installed complete new extruder with hotend upgrade and almost destroyed this one as well. Old heat brake was bent when I dissasembeled the old hotend, and the filament started to push out from the top betwen the heatbrake and heaterblock. I never noticed Z-hop not working problem before, and I assume it was working until now, becouse last succesful printed model was about 250mm tall and it printed great in PLA without artefacts. When first crash occured I had OrcaSlicer 2.2, I created new filament profile for PA-CF (from generic template) and did few small prints with OK results (holow open top box for example - bad choice obviously that is why i did not notice this problem during test prints). Then printed 2 hour long test model for hole clearance. The corners lifted up (I didn't use brims), Z-hop was not working I presume, and hotend crashed and bent the heatbrake. there was a blob of PA-CF on the hotend, when the print finished.
I now upgraded to completley different extruder and hotend combo, flashed new Marlin2 firmware with changes for new extruder/hotend, and updated to OrcaSlicer 2.3.0. I now have this problem with PLA sa well. Luckily I was testing with PLA, as the nozzle was dragging over the printed model and for now it seems the hotend survived. I didn't reslove this issue yet and I will try to adjust the Z offset and report in the evening.

**Comment by bradyjoh** [comment]
I was also having this issue, using the latest nightly 2.3.2-dev bd6cfd6. I couldn't get Z hop to work no matter what I tried. I verified by watching the nozzle scrape across whatever I printed, but also enabling the travel view inside the OrcaSlicer Preview. I tried spiral, normal (vertical lift), as well as Slope and Auto.

<img width="425" height="274" alt="Image" src="https://github.com/user-attachments/assets/eec67dcf-eab0-45db-894b-0e240672c663" />

I had been using 0 as my values for "Only lift Z above" and "Only lift Z below" as I figured that would mean the feature was disabled and it would always work. Turns out that's not how it works. Now I have it set to everything above 0 and below 300 (my max Z height) and huzzah! I can see the Z hop happening in the slicer now, and it works on the printer now.

I still have the "Reduce infill retraction" Process setting set. I am not using Z offset in my Printer settings. 

Hope this helps someone. I see this issue is closed so I'm not sure if maintainers are picking up that it's still confusing so I'll ping @MxBrnr  and @igiannakas  just to be safe.

**Comment by daef** [comment]
> I had been using 0 as my values for "Only lift Z above" and "Only lift Z below" as I
> figured that would mean the feature was disabled and it would always work.
> Turns out that's not how it works.
>
thanks so much! i was looking for my error for ages now, especially since the mouse-over text says it's only enabled for
"positive values"... is 0 positive? dunno... but -1 is not a valid value, so i figured 0 must be off... alas it's not
