### ISSUE TITLE
Paint of brim feature (Prusa slicer - PR port)

### ISSUE THREAD

**Issue by Eldenroot** [SoftFever/OrcaSlicer#3131]
**Is your feature request related to a problem? Please describe.**
(https://github.com/prusa3d/PrusaSlicer/pull/11903)

Really promising PR for one of the most wanted features - painting of brims :) 

Would be great to merge it when it will be ready and done :)

**Which printers will be beneficial to this feature**
All

**Describe the solution you'd like**
Port this PR once be ready.

**Describe alternatives you've considered**
Also extend this to fuzzy skin feature!

**Comment by arekm** [comment]
Brim painting would be a really good generic feature (comment, so search engine for issues will hopefully pick up "brim painting" phrase).

For example I like mouse ear brim but auto for it puts these not where I would like to see them (like puts it in some "internal" place etc).

**Comment by Snuff1eupagus** [comment]
You have been able to block brims since 2021 as demonstrated by Swiss_Cheese. further development is a waste of time, lets fix things that need fixing effect production.



![Blocked_ brims](https://github.com/SoftFever/OrcaSlicer/assets/95652334/53af18d3-bcce-41d4-bc9d-f00a6316fcc0)


![Blocked_ brims02](https://github.com/SoftFever/OrcaSlicer/assets/95652334/be1d0141-8200-46c3-8730-56feb11e2009)


Learn first, then focus on whats important.

**Comment by rdbischoff** [comment]
I would love to have brim painting for things like articulated toys. Would be great to have brims in some places and not in others like in between the linked pieces.

**Comment by Snuff1eupagus** [comment]
@rdbischoff 

Maybe this will solve the problem for you.

https://www.youtube.com/watch?v=6CRqNk_JUj4

**Comment by rdbischoff** [comment]
> @rdbischoff
> 
> Maybe this will solve the problem for you.
> 
> https://www.youtube.com/watch?v=6CRqNk_JUj4

cool. I will check out the video. THANK YOU!!
