### ISSUE TITLE
1.9-Dev: Crash when selecting filament

### ISSUE THREAD

**Issue by igiannakas** [SoftFever/OrcaSlicer#3202]
### OrcaSlicer Version

1.9-Dev

### OS version

Mac OS Sonoma

### Printer

X1 Carbon

### How to reproduce

Select a model - go to objects and select a filament from the drop down. Application crashes.

### Actual results

![image](https://github.com/SoftFever/OrcaSlicer/assets/59056762/de7870b2-f875-4c3c-b88d-fa629914a44a)

Above is the code segment that crashes.

### Expected results

Should not crash

### Project file & Debug log uploads

N/A

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by igiannakas** [comment]
@Noisyfox @SoftFever @Ocraftyone  have you seen this on your builds?

**Comment by zviratko** [comment]
https://github.com/SoftFever/OrcaSlicer/issues/3134

btw I'm pretty sure I saw either an issue or a commit fixing that (and obviously failing) before I filed it, but I couldn't find it

**Comment by Noisyfox** [comment]
I can reproduce this issue too. Will take a look.

**Comment by Noisyfox** [comment]
This issue was introduced in #2905. 
https://github.com/SoftFever/OrcaSlicer/blob/6bb0d5ec30559f9d54556da1e55d484363ed090b/src/slic3r/GUI/GUI_ObjectList.cpp#L5536-L5541
This piece doesn't work on MacOS, due to the existence of this
https://github.com/SoftFever/OrcaSlicer/blob/6bb0d5ec30559f9d54556da1e55d484363ed090b/src/slic3r/Utils/MacDarkMode.mm#L270-L293

**Comment by igiannakas** [comment]
Closing as PR above fixes it.
