### ISSUE TITLE
Collision Warning Ovals are insufficient for Bambu X1C

### ISSUE THREAD

**Issue by DesmoMAS** [SoftFever/OrcaSlicer#3474]
### OrcaSlicer Version

1.9.0-beta

### OS version

macOS 14.1.2

### Additional system information

CPU: M1 Ultra, 20 Cores
RAM: 64GB
Display Card: Apple M1 Ultra built-in

### Printer

Bambu X1 Carbon

### How to reproduce

Add objects to the print bed.  Set the plate to print-by-object.  Place the objects with sufficient clearance for the anti-collision ovals.  
![Orca](https://github.com/SoftFever/OrcaSlicer/assets/155746812/f11c1aed-7ee3-4a86-96fd-1095bb013930)

### Actual results

When objects are printed, the print head collides with neighboring objects (on the right hand side where the micro LIDAR hangs off) due to insufficient clearance.  Thankfully in this case I was printing thin TPU wipers so the previously printed part simply deflects without disruption or damage.
![Result](https://github.com/SoftFever/OrcaSlicer/assets/155746812/cc856e46-d8f6-46fb-b03e-c8373178185d)

### Expected results

Print should complete without collision between print head assembly and previously printed parts.  

### Project file & Debug log uploads

[OrcaCollisionIssue.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/13843158/OrcaCollisionIssue.3mf.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by DesmoMAS** [comment]
Bambu Studio collision ovals appear to be wider, in comparison.  I have not tried to replicate with Bambu Studio boundaries but when checking the build plate markings, the Bambu spacing is clearly wider.  Issue is specific to the micro-lidar unit hanging off the side of the print head, as the head would have easily cleared otherwise.  Here's what the same parts in Bambu Studio look like with their anti-collision rings:
![Bambu](https://github.com/SoftFever/OrcaSlicer/assets/155746812/091ee9b9-e04a-4c86-a185-576afded07c7)

**Comment by dstulken** [comment]
If the toolhead is that asymmetrical, I would say that even the Bambu behavior is a bug... or at least, an opportunity for improvement.  You would want the clearance boundary to also be asymmetrical to match the actual physical constraints.

**Comment by HunterzNL** [comment]
I have had a collision with my print because of this :( . I hope it doesn't effect my printer. 
Orca, please fix this. 

My situation(more info): https://www.reddit.com/r/BambuLab/comments/1dhfmge/print_by_object_collision_orcaslicer/
![print-by-object-collision-orcaslicer-v0-d92utiptmz6d1_jpg](https://github.com/SoftFever/OrcaSlicer/assets/174203183/2b81c427-54b8-4a2c-a2ba-a2ef72782e50)

![print-by-object-collision-orcaslicer-v0-rp7kvhltmz6d1_jpg](https://github.com/SoftFever/OrcaSlicer/assets/174203183/6a58af66-3adf-40a1-b1a8-daa25800bbcb)
![print-by-object-collision-orcaslicer-v0-0ym824utmz6d1_jpg](https://github.com/SoftFever/OrcaSlicer/assets/174203183/70c6de20-6bde-4242-b752-0d73b7d18275)
![print-by-object-collision-orcaslicer-v0-rvzm0teumz6d1_jpg](https://github.com/SoftFever/OrcaSlicer/assets/174203183/f9608745-bc55-40ea-8efb-59ec9223fdce)
