### ISSUE TITLE
Slow down for curled perimeters is overriding bridge speeds (for actual bridges) with overhang speed (75%,100%)

### ISSUE THREAD

**Issue by sleewok** [SoftFever/OrcaSlicer#3598]
### OrcaSlicer Version

2.0.0-dev

### OS version

Windows 11

### Printer

Ender 3 Pro w/Klipper

### How to reproduce

Load a model with a bridge. 

Enable the following: 

- Slow down for overhangs
- Slow down for curled perimeters

Slice the model.

### Actual results

The bridge speed is ignored and the overhang speed is used. 
![image](https://github.com/SoftFever/OrcaSlicer/assets/304940/678e7a7a-0828-4a09-89cd-7d62c01546b1)

Disabling "slow down for curled perimeters" allows bridges to run at the defined speed.
![image](https://github.com/SoftFever/OrcaSlicer/assets/304940/248e6a15-b73f-42a2-b0af-d2f41a32ac44)

### Expected results

The bridge speed should be used since it is a bridge and not an overhang.

### Project file & Debug log uploads

[bridge-test.zip](https://github.com/SoftFever/OrcaSlicer/files/13890410/bridge-test.zip)

### Checklist of files to include

- [X] Project file

**Comment by sleewok** [comment]
#2056

**Comment by igiannakas** [comment]
![image](https://github.com/SoftFever/OrcaSlicer/assets/59056762/edaafff3-23db-4951-a15f-c824d0aa801f)

Opened your project - cannot replicate. The perimeter is printed with the slowdown speed and the bridge is printed with the bridge speed with slowdown for curled overhangs enabled. The perimeter of the bridge is not classed as a bridge perimeter but rather an overhang perimeter and will always be printed with the slowdown for overhangs value when the curled algorithm is enabled. The reason for this is because when you're printing shapes that benefit from this feature (i.e. with overhangs) you dont want the printer accelerating when the overhang increases and the perimeter prints in mid air.

Like this for example:

![image](https://github.com/SoftFever/OrcaSlicer/assets/59056762/80f2d9f2-306f-46c1-92c5-861f77ad911d)

vs. 

![image](https://github.com/SoftFever/OrcaSlicer/assets/59056762/e599fb9b-5df3-47de-aa47-7e4676786e62)
