### ISSUE TITLE
Variable temperature based on flowrate

### ISSUE THREAD

**Issue by Vanilla009** [SoftFever/OrcaSlicer#3646]
**Is your feature request related to a problem? Please describe.**
Increasing temperature increases flow rate but brings with it it's own set of problems. For high flow printing, I sometimes have to turn the temperature up, which isn't the best solution.

**Which printers will be beneficial to this feature**
Printers with hotends that can change temperature quickly and/or high speed printers. (I have a phaetus Rapido, which can change temperature pretty quickly.)

**Describe the solution you'd like**
Settings to set what temperatures should be set for what flow rates. Maybe also something for how fast the temperature changes or pid parameters.

**Describe alternatives you've considered**
Upping the temperature or manually adjusting temperature in the gcode.

**Comment by kylek29** [comment]
This is something I've mentioned (never created a formal request) and thought about. I wouldn't mind testing even a prototype to see how well it works. There has also been a post on Prusaslicer about something similar.

To give a use case example, many PLA filaments change their sheen depending on cooling/temp (e.g. eggshell to gloss). A model that has a lot of variation in layer times needs a longer min time per layer or you'll get glossy streaks. I routinely print about 5 deg over normal with my PLA to up the flow rate for speed, but this has negative effects for overhangs (increased sagging, etc.), and the aforementioned sheen streaking introduced on shorter layers.

Being able to tie a "temperature boost" to layers that have a higher predicted flow rate might work, since short layers are less likely to deplete the heat capacity of the nozzle as longer high flowrate layers will.

**Comment by eoyilmaz** [comment]
This video clearly shows the benefits of this feature:

[![Variable Temperature 3D Printing](https://github.com/user-attachments/assets/5704442e-f2bb-435b-8206-152f4a01aef3)](https://www.youtube.com/watch?v=P6Y8uUPd3yg)
