### ISSUE TITLE
Supprt wall loops

### ISSUE THREAD

**Issue by Alexx40in** [SoftFever/OrcaSlicer#3825]
Please add the option "Support wall loops" from Bambu Studio or a similar option "With steath around the support" from Prusasliser

![image](https://github.com/SoftFever/OrcaSlicer/assets/48121823/ecd7c450-b24d-4a7f-9f80-385dd1c38faa)

![image](https://github.com/SoftFever/OrcaSlicer/assets/48121823/b3c694b3-71e4-45cc-94ab-7284d9f0aa15)

**Comment by faith-healer** [comment]
+1 there, need that

**Comment by AJolly** [comment]
Its weird, I can search and it says the settings there, but i cant access it

**Comment by toddanglin** [comment]
Rather than creating another issue, reviving this issue since it's been asked several times and it's precisely what I came here to say/ask. Can anyone shed light on why this setting is available in Bambu Studio/PrusaSlicer but not in OrcaSlicer?

What's odd, is that in the past OrcaSlicer has behaved similarly (adding support walls), but now I'm unable to control that setting and the generated supports are worse.

**Comment by digital0785** [comment]
why is this closed as not planned when it's a thing in everything this is based off and is kinda necessary for quality support interfaces vs them dangling at the edges 

i swear this was in there before until searching for this just now

**Comment by toddanglin** [comment]
@digital0785 FWIW, I have since found this setting *is* available in Orca, but only when you're using the following Support settings:

1) Type: Tree (manual OR auto)
2) Style: Tree Slim OR Tree Strong OR Tree Hybrid

When using those Support types, you'll see the setting for Support Wall Loops become available. ¯\_(ツ)_/¯

**Comment by digital0785** [comment]
> [@digital0785](https://github.com/digital0785) FWIW, I have since found this setting _is_ available in Orca, but only when you're using the following Support settings:
> 
> 1. Type: Tree (manual OR auto)
> 2. Style: Tree Slim OR Tree Strong OR Tree Hybrid
> 
> When using those Support types, you'll see the setting for Support Wall Loops become available. ¯_(ツ)_/¯

yes but it's needed for standard supports as well. I've done this in super and prusa slicer ages ago

prusa 2.6
![Image](https://github.com/user-attachments/assets/9ddd0e58-405a-42d9-a7e2-4183150994b9)

![Image](https://github.com/user-attachments/assets/4748271e-d1e9-49a9-8713-70d50286f02d)

vs orca 2.3

![Image](https://github.com/user-attachments/assets/a78e6356-8d4d-4ccb-91e7-e4a47075d8de) 

this specific model it's less of an issue but there is 0% chance it works here .. because it's trying to turn around over thin air .. it made that whole area look like crap on a 15 hour print lol.. heck even just having the option to rotate JUST the first interface layer would resolve the issue to be able to get it to align better with the supports but. using grid kinda works but it'll still have ends that dangle over but it's better then default for sure. 

![Image](https://github.com/user-attachments/assets/0d40d7a7-5cfa-4f5f-ba3a-848bd61b6f3c)

supports is the absolute worst part of orca it's super frustrating that it never gets any work and given the other 3 slicers that are off the same backbone done have the issue theres no excuse .. 

and with multi material being a thing for having 0 gap supports kinda need reliable interfaces lol. For the last model switching to tree supports not only adds 5 hours but doesn't really save filament  it's 10g less which is pointless.

**Comment by digital0785** [comment]
> Agree. It would be nice to have full control over this support setting under all conditions. Not sure why Orca made the decision to hide it for traditional supports.
> 
> In one of my primary use cases where I need this control, I still need traditional supports, and I've found using "Tree Hybrid" will generate traditional supports where I need them (while giving me access to the Support Wall Loops). Clearly, YMMV.

yea usually that works but on this particular model for whatever reason it uses ~10g more and takes longer LOL this is same settings just hybrid tree vs snug normal lol

![Image](https://github.com/user-attachments/assets/3db3b62b-15ab-4207-ab26-060f48f56c25)

![Image](https://github.com/user-attachments/assets/d0e8a670-6f67-4a9a-95bd-a849f666ded0)

**Comment by digital0785** [comment]
> [@digital0785](https://github.com/digital0785) FWIW, I have since found this setting _is_ available in Orca, but only when you're using the following Support settings:
> 
> 1. Type: Tree (manual OR auto)
> 2. Style: Tree Slim OR Tree Strong OR Tree Hybrid
> 
> When using those Support types, you'll see the setting for Support Wall Loops become available. ¯_(ツ)_/¯

in an odd twist of fate looks like i've discovered a bug.. this actually works IF and only if you have build plate only off lol also apparently support critical means something completely different to orca then myself because a 90+ overhang isn't "critical" lol

![Image](https://github.com/user-attachments/assets/2b75fbeb-a3c6-4692-897a-e822d3767e17)

![Image](https://github.com/user-attachments/assets/cbd49575-1c73-48eb-9cae-1929084794aa)

![Image](https://github.com/user-attachments/assets/f4564448-6d41-41c3-a5fc-e2df6cd6d057) 

so i guess the "work around" is hybrid with blockers or manual.. but definitely isn't working proper.. devs PLEASE put some effort into supports/ bridging it's really a huge short coming and everything that gets opened about it gets closed for "not planned" when its quite literally the worst part of the slicer.. I'll gladly take a delay on some new features coming out for proper working anchored bridges / multi layer bridges and proper supports without bugs

**Comment by PlasmaKirill** [comment]
+1 really need this!
How to add an outer 1 wall for the supports (support outline)? 
It's in the PrusaSlicer, but I can't find it in OrcaSlicer.

OrcaSlicer (?)
![Image](https://github.com/user-attachments/assets/75eccfb3-b032-4885-ac43-61f6ef268b00)

PrusaSlicer (support_material_with_sheath)
![Image](https://github.com/user-attachments/assets/80f4902d-3603-4341-b033-1fc1a178d093)

**Comment by digital0785** [comment]
> +1 really need this! How to add an outer 1 wall for the supports (support outline)? It's in the PrusaSlicer, but I can't find it in OrcaSlicer.
> 
> OrcaSlicer (?) ![Image](https://github.com/user-attachments/assets/75eccfb3-b032-4885-ac43-61f6ef268b00)
> 
> PrusaSlicer (support_material_with_sheath) ![Image](https://github.com/user-attachments/assets/80f4902d-3603-4341-b033-1fc1a178d093)

this dev build has it :) they're working on it currently
![Image](https://github.com/user-attachments/assets/8403f11d-ac51-48f9-aa80-174fcd4c61cd)

listed here https://github.com/SoftFever/OrcaSlicer/pull/8212

**Comment by PlasmaKirill** [comment]
How to download this 2.3?

**Comment by digital0785** [comment]
> How to download this 2.3?

They mention how to get it in that post
