### ISSUE TITLE
Seam Edge: Highlight Angle Option, Sharpest Corner

### ISSUE THREAD

**Issue by TheAtomicSoul** [SoftFever/OrcaSlicer#3915]
Please add two options for Seams: 

1:  Seam Position: Add "Sharpest Corner"
Also consider adding "Primary and secondary" options, so "Primary; Sharpest corner. Secondary: Back", to help ensure it's location is controlled in any situation, like a cylinder with a sharp edge only halfway up. 

2: Seam Painting: Add "Highlight Angle" option to allow automatic selection based on angles, similar to how  "Highlight Overhangs" works for support painting.

**Comment by TheAtomicSoul** [comment]
Would really like this option added: I'd think it's implementation wouldn't be too difficult.

**Comment by Vantage-DS** [comment]
Seconded, I have major issues with seam painting.
Cura's seam adaptability is much better.

**Comment by Nandox7** [comment]
Plus one to this.
Getting problems printing a print in place part with gears, slicer decides to move the seam to where the gears mesh as it hides it. That is true but causes the gears to fuse together due to this.

![image](https://github.com/SoftFever/OrcaSlicer/assets/117827/a9fcc23a-2e91-435a-a90e-5fcc73707a93)
![ShareX_Xgd5QWIytj](https://github.com/SoftFever/OrcaSlicer/assets/117827/734c928b-52aa-464e-91ef-40e6135a0c4a)

Opposed to Creality Print slicer that has the option "Sharpest Corner" that moves it away from there and the part prints well.
![image](https://github.com/SoftFever/OrcaSlicer/assets/117827/1a27c6a7-7c64-4308-bb61-bd05fe3e5146)

**Comment by hmenzagh** [comment]
This is the biggest flaw of orca imo, why are we so little asking for this ?

**Comment by TheAtomicSoul** [comment]
Is there any way to reopen this?

**Comment by Nandox7** [comment]
Open a new one and link to this one?
Makes no sense this was closed.

**Comment by Nandox7** [comment]
Opened #7414
