### ISSUE TITLE
Post Processing Scripts are not applied to files sent to a bambu lab printer

### ISSUE THREAD

**Issue by samwiseg0** [SoftFever/OrcaSlicer#3974]
### OrcaSlicer Version

1.9.0

### OS version

13.4.1 (c) (22F770820d)

### Printer

Bambu Lab X1

### How to reproduce

1. Set a post processing script to be ran.
1. Slice any model
1. Use "Export all sliced file" or send the file to the printer and then download it from the printer. 

### Actual results

The 3mf generated will contain a gcode file that _was not_ processed by the post processing script. This also applies to any job you send to the printer via the cloud or LAN. 

The only way to have the printer use gcode that was processed is by saving the exported gcode from orca and uploading it manually to the printer. 

This is confirmed by this thread. https://forum.bambulab.com/t/post-processing-scripts/25517/1

### Expected results

A post processing script should process all generated gcode files by the slicer. 

### Project file & Debug log uploads

This file should have been processed by ArcWelder but was not.  

[Voron_Design_Cube_v7_ABS_45m52s.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/14160176/Voron_Design_Cube_v7_ABS_45m52s.3mf.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by samwiseg0** [comment]
bump

**Comment by function3d** [comment]
Hi Orca Slicer Team,

Please consider reopening this issue. After doing a deep dive into the code of `src/slic3r/GUI/BackgroundSlicingProcess.cpp`, there is a clear architectural oversight causing post-processing scripts to be skipped entirely during **3MF Export** and **Wi-Fi uploads** on **non-BBL (Bambu Lab) printers**.

#### The "BBL-Only" Half-Fix

We noticed that this issue was likely closed because a fix *was* implemented specifically for Bambu Lab printers. Around line 207, right after `export_gcode` populates the temporary path, the script runner is forced inline:

```cpp
if(m_fff_print->is_BBL_printer())
    run_post_process_scripts(m_temp_output_path, false, "File", m_temp_output_path, m_fff_print->full_print_config());

```

While this successfully resolved the bug for BBL hardware utilizing the 3MF Wi-Fi pipeline, it created a strict divergence in the slicing workflow. For any other printer vendor setup (Creality, Voron, Klipper-based setups, etc.), `m_temp_output_path` remains completely **unprocessed/raw** at this stage of the execution.

#### The Finalization Branch Failure

Right after that inline conditional, the code execution reaches the step finalization branch:

```cpp
if (! m_export_path.empty()) {
    if(!m_fff_print->is_BBL_printer())
        finalize_gcode(); // Runs post-processing correctly for standard .gcode exports
    else
        export_gcode();
} else if (! m_upload_job.empty()) {
    prepare_upload();     // Sends the job via Wi-Fi
}

```

* **Why regular G-code Export works:** For non-BBL printers, it routes to `finalize_gcode()`, which contains a fallback call to `run_post_process_scripts()`.
* **Why Wi-Fi Upload fails:** It routes directly to `prepare_upload()`. If `m_upload_job.upload_data.use_3mf` is true, it immediately grabs `m_upload_job.upload_data.source_path`. Because it completely bypasses `finalize_gcode()`, non-BBL printers sending a 3MF via Wi-Fi **never** have their post-processing scripts executed.
* **Why "Export plate sliced file" (.3mf to disk) fails:** It bypasses this entire pipeline and goes straight to the UI plater packaging logic, entirely missing the post-processing script trigger.

#### The Consequence

If a user runs a non-Bambulab setup but uses the `.3mf` ecosystem for wireless printing or plate saving, Orca Slicer completely forgets to pipe the G-code through the post-processing script runner because of the `is_BBL_printer()` restriction upstream.

#### Proposed Solution

The script processing needs to be decoupled from the destination format or vendor. `run_post_process_scripts` should safely run on `m_temp_output_path` for **all** printer profiles upstream, or explicitly handled inside `prepare_upload()` when `use_3mf` is true, as well as in the plater's 3MF export routine.

Could we please reopen this to ensure post-processing scripts work universally across all export types? Thanks!
