### ISSUE TITLE
Wrong value for filament start g-code M900 and nozzle_diameter 0.4 (Prusa generic PLA @MK4)

### ISSUE THREAD

**Issue by bsamorodov** [SoftFever/OrcaSlicer#4104]
### OrcaSlicer Version

1.9.0

### OS version

Ubuntu 22.04.3 LTS

### Printer

Prusa MK4

### How to reproduce

Goto filament settings of Prusa generic PLA @MK4, Advanced window
Look at M900 line and a value for 0.4 nozzle. It's 0.026. According to PrusaSlicer 1.7.1 it should be 0.05.
And I've sorted the given m900 values by a nozzle size. Here they are:
-----
0.8   0.015
0.6   0.03
0.5   0.035
0.4   0.026
0.35 0.06
0.3   0.07
0.25 0.14
-----
Sure, one may notice that the 0.05 value is more appropriate for the 0.4 nozzle size.

### Actual results

Get the value 0.026 for the 0.4 nozzle.

### Expected results

Get the value 0.05 for the 0.4 nozzle.

### Project file & Debug log uploads

[debug_Thu_Feb_15_14_00_22_184139.log.zip](https://github.com/SoftFever/OrcaSlicer/files/14302981/debug_Thu_Feb_15_14_00_22_184139.log.zip)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by rcloran** [comment]
My understanding is that since M572 is emitted immediately after M900, and because OrcaSlicer only supports the MK4 in IS mode, the M900 values will be ignored. But ... even the M572 values are out of whack with the current Prusa profiles.

I think it'd be neat if M572 was emitted based on filament properties that can be set in the Orca UI, and created #5056 to suggest that. One problem would be how it handles M900 if you're running a custom MK4 profile that disables input shaping.

I'd be happy to take on getting the correct M572 values emitted as part of #5056 , and am curious to know whether completely removing the M900 would break something for you.
