### ISSUE TITLE
The new release dialog window is not resizeable even though it acts like it should be

### ISSUE THREAD

**Issue by julie777** [SoftFever/OrcaSlicer#4122]
### OrcaSlicer Version

1.9.0

### OS version

Windows 10

### Printer

p1p

### How to reproduce

1. start an older version of Orca Slicer
2. the new version dialog should be shown
3. hover over the resize handle in the lower right corner of the dialog and the cursor changes to the resize cursor
4. left click and hold and try to resize

### Actual results

the window does not resize

### Expected results

The window should resize

The new release dialog is not resizable even though it shows a size control in the lower right corner and the cursor changes to a resize cursor when hovered over.

The width does not match the text which makes it difficult to read because it must be scrolled to read the end of each line.

![image](https://github.com/SoftFever/OrcaSlicer/assets/5090005/46bd989f-6154-4520-adff-5c5bffbb9182)

### Project file & Debug log uploads

None

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by dstulken** [comment]
I can confirm the same behavior on the Mac (arm64) build.   The cursor changes to the resize cursor, but the window is not resizable.

I can also confirm the text being too wide for the window.  Interestingly, on the Mac side, there is no horizontal scrollbar available... and the text overlaps on top of the vertical scroll bar, rather than underneath it.

(Screenshot attached.)


<img width="670" alt="OrcaSlicer New Version Text Overlap" src="https://github.com/SoftFever/OrcaSlicer/assets/43459037/c8035266-a01d-4e39-92d9-c55a27bebd01">
