### ISSUE TITLE
Minimum Layer Time Setting

### ISSUE THREAD

**Issue by codyglad** [SoftFever/OrcaSlicer#4191]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I print minis on my 3d printer. When there are really short layers the print will fail because the plastic doesn't have time to fully solidify. What I end up doing is printing a cylinder alongside the mini where each layer takes 7 seconds. This allows the printer to print the mini layer, then let it cool for 7 seconds before it prints the next layer. 

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

It would be really nice if there was a setting for minimum layer time that would allow the filament to cool. Basically what it would do is print the layer, and if it took less time than the minimum layer time, it would move the nozzle to a safe location and do a pause for the remainder of the minimum layer height.

### Additional context

Cura has this setting and it operates as described.

**Comment by kylek29** [comment]
I think this exists in the Filament settings as I have to use it with certain filaments. It's kinda labeled in a confusing way (IIRC), I'll post back a screenshot when I get to my desk.

**Comment by ShaneDelmore** [comment]
I think it is one of these two identically labeled "layer time" boxes, but I am not entirely sure how to interpret them so you would need to experiment. It would be nice if there was just a clearly labeled minimum layer time somewhere as most people expect to find.

What does layer time have to do with cooling fan?  Why are two labeled the same thing?  Is one min layer time and one max layer time, no that wouldn't even make sense, but I have a feeling it is one of these.

<img width="686" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/4604933/d47df753-84db-4936-97ee-7105d774c867">

**Comment by abychko** [comment]
I saw something similar in FlashPrint. I tried to print Nazgul fugure on FF https://thangs.com/designer/FotisMint/3d-model/Nazgul%20Figure%20-%20Lord%20of%20the%20Rings%20%28Pre-Supported%29-960887 and it moves extruder away for 5-7 seconds after each layer while it prints the sword

**Comment by codyglad** [comment]
abychko that is exactly what I would like. 
The fan speed thing will slow down the print so that the layer takes that amount of time, but if you have a really small layer, the heat of the nozzle will melt the plastic.
When printing really small parts, when the layers are small, that you need to print a layer, then pull the nozzle away (to let the layer cool) before printing the next layer.

**Comment by igiannakas** [comment]
I would really avoid implementing a feature like this in the slicer.

Why:
1. Moving the nozzle away from the print and letting it sit idle without printing means it looses pressure and oozes filament. When it comes to resume, the initial extrusion will be under extruded significantly.
2. There is a method to do this already - add a primitive - cube to the print bed and place it as far away as possible from the printed model. Set your cube's height to match the model size. this way you are extending the layer time because the extruder has to travel to the other object plus you dont get any oozing and you're also keeping your nozzle primed when you're back to the main object. You can also set the speed of the cube independently to be really slow if you need a lot of time for each layer.

There is a PR that I've opened recently that aims to provide some improvements to the handling of print speeds when needing to reduce for minimum layer time here. It doesnt solve this issue but it will help you get better external wall finish for your prints.https://github.com/SoftFever/OrcaSlicer/pull/5148

**Comment by jefftopp1984** [comment]
I want to do the same thing but cannot find the correct variable or if statement. I DO NOT want to SLOW the print speed because my printer is calibrated for 250mm/s and slowing causes print quality issues. I also DO NOT want to run the fan because I print ASA and this will WARP the print. All of the solutions that Google's stupid AI suggest are SLOWING OR USING THE FAN.

**Comment by NeighNeighNeigh** [comment]
> I want to do the same thing but cannot find the correct variable or if statement. I DO NOT want to SLOW the print speed because my printer is calibrated for 250mm/s and slowing causes print quality issues. I also DO NOT want to run the fan because I print ASA and this will WARP the print. All of the solutions that Google's stupid AI suggest are SLOWING OR USING THE FAN.

I think the suggested solution in the comments of this issue is the appropriate solution. That is adding a primitive (cylinder works best) to the print bed as a sacrificial time waster. It’s extremely simple and doesn’t introduce extrusion issues present when pausing and letting the hotend ooze.
