### ISSUE TITLE
letters disappear in slicing

### ISSUE THREAD

**Issue by plexi32** [SoftFever/OrcaSlicer#4201]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

1.9.1

### Operating System (OS)

Windows

### OS Version

Windows 11

### Printer

BambuLab X1C

### How to reproduce

whatever i do, always the same letters do not reflect in the slicing result.

### Actual results

not all letters are visible

### Expected results

all letters are visible

### Project file & Debug log uploads

![letters](https://github.com/SoftFever/OrcaSlicer/assets/58932224/d12d05fc-a3f4-41d9-953c-d027e41b95cf)
![not all letters anymore](https://github.com/SoftFever/OrcaSlicer/assets/58932224/5a183b08-69e1-47f1-b883-7082ab4656ce)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by pgifford** [comment]
It would help if you included at least a project file. I've had this happen, though not to this extent, with small text and the Arachne wall generator.  Switching to classic wall generator solves the problem for me.  Since you didn't provide a project file or any details whatsoever about the print settings your issue is impossible for the developers to work.
