### ISSUE TITLE
Feature request: Add retraction calibration tool

### ISSUE THREAD

**Issue by erickdredd** [SoftFever/OrcaSlicer#439]
The new calibration tools have been fantastic, however retraction calibration is sorely missed now that just about everything else is so easy and convenient. I would love to see something like the towers generated by [this tool](http://retractioncalibration.com/) built into the slicer, as it's one of the best and quickest ways to tune retraction that I'm personally aware of.

**Comment by ab3dgeek** [comment]
yes that one looks like a good tool, it sure would be a nice and much needed addition to the already nice selection of calibration tools.

**Comment by adamfilip** [comment]
Please also include the ability to tune Detraction/extra restart as well.

**Comment by SoftFever** [comment]
Added in 1.6.3 beta

**Comment by nilbest** [comment]
I know this is a closed Feature request, but I'm unsure if this is rolled out in 1.8.1.
I'm missing the feature for setting up the retraction speed. A toggle implemented in the other calibration tools would be great.
For example, setting up TPU with a Bowden extruder is right now a pain in the ass because of that.
I still have to set it up in Curra first or use this page https://teachingtechyt.github.io/calibration.html#retraction .
![Retraction_Speed](https://github.com/SoftFever/OrcaSlicer/assets/104395997/9141f05f-f7ef-460e-be2a-1b2a3bdb70b4)
An in-slicer integrated function would be great. Maybe a mash of the normal retraction distance is changeable via a selection like in the temp tap.
![Orca_Retraction](https://github.com/SoftFever/OrcaSlicer/assets/104395997/851ccd91-8bad-4e08-ac67-6b338fae1849)
![Orca_Temp](https://github.com/SoftFever/OrcaSlicer/assets/104395997/4ec22bc6-e5bf-42c1-a1e0-9cf0ebd6ff53)
![Orca_Retraction_Added](https://github.com/SoftFever/OrcaSlicer/assets/104395997/98f232c2-43fe-45d1-ac57-ae950ea3ba3b)
