### ISSUE TITLE
Tree support (Slim) not behaving correctly

### ISSUE THREAD

**Issue by srbjessen** [SoftFever/OrcaSlicer#4590]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

Windows

### OS Version

10

### Printer

Biqu BX Klipper

### How to reproduce

Slicing an object in BambuLab, compared to OrcaSlicer yields very different results.

### Actual results

![image](https://github.com/SoftFever/OrcaSlicer/assets/92088582/6a8003a7-5eba-4f90-adeb-2e9c34a83ff2)

### Expected results

Although they are 2 "different" slicers, i was expecting to see more similar results than the actual result.

### Project file & Debug log uploads

[H4-Stole-Donna.zip](https://github.com/SoftFever/OrcaSlicer/files/14657791/H4-Stole-Donna.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by tlhintoq** [comment]
I'll add to this rather than make a new similar bug.
Support selection just isn't working in 2.0 beta.  No matter what you pick you get the typical organic tree support.
Which also means you can't do variable layer height because those two don't go together.
![image](https://github.com/SoftFever/OrcaSlicer/assets/11351506/ae4a5ca8-f2cc-4408-90aa-36a12b81b173)
![image](https://github.com/SoftFever/OrcaSlicer/assets/11351506/d2437553-58f7-4ad3-b850-57432296076f)

**Comment by tntfriesen1** [comment]
I am **unable** to replicate this issue on 2.0.0-dev with the attached 3mf file as well as using my own profile and settings.

**Comment by tlhintoq** [comment]
![Snag_1a30be9c](https://github.com/SoftFever/OrcaSlicer/assets/11351506/7641cabf-1f74-4328-9806-6da95a6fbdfa)
Clearly set to normal|Manual and getting tree supports.
[Best+Poop+System.zip](https://github.com/SoftFever/OrcaSlicer/files/14733948/Best%2BPoop%2BSystem.zip)
