### ISSUE TITLE
Webcam not work when using Basic Auth

### ISSUE THREAD

**Issue by raphaeleduardo42** [SoftFever/OrcaSlicer#4703]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0-beta

### Operating System (OS)

Windows

### OS Version

Windows 11

### Printer

Ender 3-S1 Klipper

### How to reproduce

1. Define hostname/device ui to point to Cloudflare Tunnel address, using basic auth (traefik) and api key (moonraker)
2. Access Device Tab

### Actual results

![image](https://github.com/SoftFever/OrcaSlicer/assets/77018363/0a5f416b-4f4f-4db4-a601-77587864ad34)

### Expected results

![image](https://github.com/SoftFever/OrcaSlicer/assets/77018363/47ec3eb2-1b96-407c-a021-82dfba503e0a)

### Project file & Debug log uploads

[log.zip](https://github.com/SoftFever/OrcaSlicer/files/14746052/log.zip)

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Anything else?

Accessing through browser it works correctly, when pointing to my local address that doesn't require the basic auth to be inserted.

Removing the auth from traefik (and from orcaslicer) fix the problem, but lead to security concerns.

Could be nice to have an option to use another form of login/security like HTTP-Header. Mobileraker had this implemented, and it works flawless.

**Comment by RK392** [comment]
I'm facing a similar issue when accessing a device with Basic Authentication enabled. I've set up basic auth to protect the whole device instead of just the webcam. So I keep getting HTTP 401 Authorization Required.

I can't access Mainsail under the device tab nor upload G-Code to the printer.

Like @raphaeleduardo42 said earlier. Mobileraker has HTTP headers implemented. Using the correct HTTP headers allows me to access the printer remotely with no issues.
