### ISSUE TITLE
Split bridge speed to bridges and internal bridges (and cooling too)

### ISSUE THREAD

**Issue by Chodec80** [SoftFever/OrcaSlicer#472]
Hello everyone,
It would be nice to have individual speed setting for proper bridges and for internal bridges (first layer above infill). It is annoying to close an infill at the speed 40-50mm/s.

Related to the request above, would be also fine to separate cooling setting for bridges and internal bridges. 

Attached pictures are from Superslicer

Speed setting
![Snímek obrazovky 2023-03-12 v 12 52 47](https://user-images.githubusercontent.com/61891781/224542817-99577067-b62e-40d1-9414-593e7419b0f1.png)

Cooling setting
![Snímek obrazovky 2023-03-12 v 12 53 15](https://user-images.githubusercontent.com/61891781/224542838-11d8e754-7e89-4f4c-a134-ac718b688fd0.png)

Thank you for consideration of this proposal

**Comment by ab3dgeek** [comment]
That is a great idea! It could save a ton of time on some my prints too.

**Comment by Chodec80** [comment]
> That is a great idea! It could save a ton of time on some my prints too.

yes, it can. Second benefit is "silence" because closing of the infill doesn't need full speed of the fan.

**Comment by movinimage** [comment]
YES!  For a large flat object made of ABS/ASA or other high-warp materials, this is critical to avoiding failure. As it stands, I turn down the blower by hand while I sit by the printer! Otherwise the object pops of the build plate without fail.

Here is an example of something that fails every time unless blower is turned down...the object is 1/4" thick at the top of the first giant layer. (this object is about 7" wide.

<img width="579" alt="Screenshot 2023-09-03 at 11 05 12 AM" src="https://github.com/SoftFever/OrcaSlicer/assets/13089904/f1a202ae-6559-44ec-b145-64283a154957">

**Comment by Chodec80** [comment]
> I'm using 1.8.0 and it offers separate speed settings? Internal seems to default to 1.5 times faster.
> 
> ![Bridging speed](https://user-images.githubusercontent.com/68766/285141031-27a057b0-b951-4687-aac7-3a9ab4c7cb13.png)
Yes, they put it there few version back. For example, I use for internal bridges same speed as is defined for internal perimeter.

**Comment by jonaseymour** [comment]
Yeah, this would be great. I recently had issues with layer adhesion with my PETG prints and narrowed it down to my internal bridge cooling being too high, but it was that high to get good external bridges.

Control over these would be great.
