### ISSUE TITLE
The position of the hot bed after being set to a circle is incorrect. How can I set it?

### ISSUE THREAD

**Issue by fzxlzy** [SoftFever/OrcaSlicer#4812]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

The position of the hot bed after being set to a circle is incorrect. How can I set it?
![test](https://github.com/SoftFever/OrcaSlicer/assets/38089446/02c5a1a5-cc65-4348-a5a6-fc48baaf3e73)

### Which printers will be beneficial to this feature?

Klipper

### Describe the solution you'd like

Correct position

**Comment by TexZeTech** [comment]
Oh that is weird I didn't even understand what the issue was. Until I swapped from Dark mode.

Ya this looks like a bug to me as just the background selection isn't right on the top.


It does not happen in v1.8.1 on Linux.

I've confined this is in versions 1.9.0-alpha to 2.0.0 on Linux and the 2.0.0 version on windows.


<img alt="Screenshot_20240331_102413" src="https://github.com/SoftFever/OrcaSlicer/assets/7254540/5a84219d-8bd4-473a-92bc-fb9a9dd41800" width=80% height=80%>

I will say I'm not sure why the rectangle build plate gets the origin x / y adjust. I would just remove that or add it to both.

<img src="https://github.com/SoftFever/OrcaSlicer/assets/7254540/381d4592-6fdf-4c87-a169-7078f911192a" width=40% height=40%>

<img src="https://github.com/SoftFever/OrcaSlicer/assets/7254540/776d0a3e-5a06-4849-b9d1-bef6fd84cdc9" width=40% height=40%>
