### ISSUE TITLE
orca too slow from cura

### ISSUE THREAD

**Issue by dfctores1111** [SoftFever/OrcaSlicer#4861]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

Windows

### OS Version

win10

### Printer

ender 3 v2 neo

### How to reproduce

....

### Actual results

hi, i slice these 5 ring in cura and orca and the time between both is too high, i checked the max volumatric speed and nothing helped, i notice that gap infill take most time, but i cant disable it , tried to cheange wall from classic to archane but nothing ..

![dfdfde](https://github.com/SoftFever/OrcaSlicer/assets/130936122/f74d99ca-14ec-411e-9055-300b18b1024a)
![edeee](https://github.com/SoftFever/OrcaSlicer/assets/130936122/45296ae2-63e6-4601-9832-0153218043a7)

### Expected results

..

### Project file & Debug log uploads

..

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by DVSVIDEO** [comment]
If you attach the project (you should have) I could try to see what it does with my settings...

By the way why are you printing at such a low speed and why is the inner wall the slowest?
The outer wall is the visible one and that's why it's usually printed slower. The inner wall can be printed at double speed.
