### ISSUE TITLE
Multi-part Object Positions are Reset After Splitting to Objects

### ISSUE THREAD

**Issue by inovatorius** [SoftFever/OrcaSlicer#4868]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

Windows

### OS Version

11

### Printer

Prusa

### How to reproduce

1. Import .stl file
2. Prepare -> Objects -> Right click on object -> Split -> To Object

### Actual results

Multi-part object parts positions are reset after using split to object function, but not when using split to parts.

### Expected results

After splitting to object, parts should keep the same position just like when splitting to parts, because you can always auto-arrange them and not vice-versa. Objects have way more options for modifications while parts lack of them.

### Project file & Debug log uploads

[File.zip](https://github.com/SoftFever/OrcaSlicer/files/14872284/File.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Anything else?

<img width="1922" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/122360472/7a31a419-6d7d-4e20-b6fa-225e5f0d6ce6">
<img width="1922" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/122360472/a29fcb49-1081-476e-a712-ac5c02b07a36">

**Comment by Dochartaigh** [comment]
I can confirm this bug on MAC as well, and it's making Orca slicer UNUSABLE (I NEED to split off parts to easily change their color instead of manually selecting 1000+ triangle faces). Also broken in BambuStudio. Also moves items if you CUT them as well.

Here's a screen recording of my Mac (2023 Mac Mini M2 Pro, Sonoma OS, newest v2.0.0 Orca Slicer). The first split and you can see the inside move down. Split again (trying to get those 2x wings split off) and the bottom wing moves ALL the way down...

https://youtu.be/v0NwxjwofYk

Orca's own Wiki says "After splitting, each part stays in its original position"...
![Screenshot 2024-04-08 at 2 44 41 AM](https://github.com/SoftFever/OrcaSlicer/assets/23370177/9e0161d6-7c79-4ff1-b7ca-daf38a82a482)

**Comment by 762SPR** [comment]
I don't know why this was closed. The issue is still present on 2.2.0 / Windows. I have manual supports modeled as a separate mesh in the STL file and want them to have different infill and wall settings. When I split the mesh to different objects they auto arrange and are no longer aligned. On very rare occasion they will stay put but I can't seem to find a reliable trigger for that.

Please make it so the parts stay put when separated. As OP said, they can always be auto arranged later if that is the user's desire. Or have a check box like for cloning objects.

**Comment by hell1337hound** [comment]
Bump this is still an issue

**Comment by ddfault** [comment]
There is actually a solution to this. (At least in Orca Slicer 2.3.0 stable release, but probably earlier versions.) In the cut dialogue there is a check box you can select. **Cut to parts**. This keeps both parts as one conjoined part where you can alter each one's color and have full control to move them around between one another.

<img width="382" height="375" alt="Image" src="https://github.com/user-attachments/assets/8e48879b-dc34-4184-89be-e9e70ee4c979" />

**Comment by 762SPR** [comment]
Running 2.3.2 beta 2 this issue still persists. I think it *may* have something to do with Solidworks/step files and possibly how individual body origins are handled on load. That is just a suspicion as this doesn't seem to be a problem for everyone, I have seen several videos where it works perfectly fine. Maybe other CAD platforms export step files differently?

Anyway, here are some more details and a workaround until this bug is fixed. Pinging @hell1337hound @Dochartaigh @inovatorius if you guys are still having the problem like me.

After importing and orienting, all bodies are as one object (split is NOT checked in .step import popup as that seems to produce the error automatically)

<img width="1670" height="644" alt="Image" src="https://github.com/user-attachments/assets/2a1e8acb-c02d-4502-a636-0cdf95fd704a" />

Once split to Objects is pressed, you can see the positions get messed up. (note this also happens if split to parts is used, but less offset seems to affect them. In this test it is the same direction, but different distance)

<img width="1730" height="707" alt="Image" src="https://github.com/user-attachments/assets/45b40b1c-531a-4e79-bc05-13651ee9809b" />

However if you undo that, and right click the single object to split and *reload from disk* THEN click split to objects, it will now work without messing up positions 

<img width="1675" height="722" alt="Image" src="https://github.com/user-attachments/assets/adcc3837-979d-4d6a-9773-bd1d3566e5d7" />

Something about loading vs reloading seems to do the trick. Hope this helps!

**Comment by noahhaon** [comment]
Still an issue with 2.3.2 build c724a3f5. @762SPR 's workaround worked for me however, thanks!
