### ISSUE TITLE
Calibrations not working properly

### ISSUE THREAD

**Issue by BlackThumb** [SoftFever/OrcaSlicer#4976]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

macOS

### OS Version

Ventura 13.4

### Printer

Qidi X-Plus 3

### How to reproduce

I've tried flow calibration and Pressure Advance for Recreus Filaflex 82A TPU, but the results look the same also after tweaking.
For the Flow Calibration all the 9 squares in Pass 2 look identical and for PA Calibration I started from 0 to 0.12 (right test in the picture), then I made a second one after restarting the program from 0.1 to 0.22 (test on the left), but the two tests look identical, the 0 on right looks the same as the 0.1 on the left and the 0.12 on the right looks the same as 0.22 on the left.
![PXL_20240410_194729992](https://github.com/SoftFever/OrcaSlicer/assets/72305397/875c31f7-688b-4bd3-a9fb-2273694cd1df)

### Actual results

Doesn't change anything

### Expected results

Expecially on the PA test the two must look completely different.

### Project file & Debug log uploads

I don't add file because the tests are the same for all.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by eyduh** [comment]
Maybe have a look at the generated GCODE.

I have a similar experience on NixOS, however, inspecting the generated GCODE in the preview seems to indicate different flow rates in the first scenario. With pressure advance however it seems to reset the PA value to 0 on every layer:

For the pressure advance tower I seem to experience a similar scenario since, at the start of every layer I have a line like a so:
```
SET_PRESSURE_ADVANCE ADVANCE=0; Override pressure advance value
```

however, with the shape calibration, there is a change in PA at the appropriate places.
