### ISSUE TITLE
Error when mirroring detail

### ISSUE THREAD

**Issue by pterodaktil02** [SoftFever/OrcaSlicer#5307]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

Windows

### OS Version

Windows 11

### Printer

Voron 2.4 300 0,4mm

### How to reproduce

1.  open  stl  file from  archive
2. Make  copy and  mirror  it  for Y 
3.  Make   few  copy  of  both  details 

[7_Skoba_p2.zip](https://github.com/SoftFever/OrcaSlicer/files/15264974/7_Skoba_p2.zip)

### Actual results

If  use  autoorientation   give  error
It  say   that  Object  has zero size and cant be arranged
With  manual  placement    it say  "Fatal error occured "Violation of access rights"
Please save project and  restart programm
Save   project and    import  geomery   again  -  make same error 
If  i  place details   in  prusa   and  open  project  in Orca - it can  be sliced 
![Screenshot_1](https://github.com/SoftFever/OrcaSlicer/assets/65681281/27e21af7-4e20-40cd-905c-4e02590b0cc1)
![Screenshot_2](https://github.com/SoftFever/OrcaSlicer/assets/65681281/c8ca3c72-d581-45d4-ac6a-b9ac4a2195b1)

### Expected results

No error   on  mirroring detail

### Project file & Debug log uploads

Log attached
[debug_Thu_May_09_19_44_08_17240.log.zip](https://github.com/SoftFever/OrcaSlicer/files/15265073/debug_Thu_May_09_19_44_08_17240.log.zip)
[project.zip](https://github.com/SoftFever/OrcaSlicer/files/15265103/project.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Anything else?

/

**Comment by Matszwe02** [comment]
The same happens to me

![image](https://github.com/SoftFever/OrcaSlicer/assets/49353902/27d609c6-72b2-413c-878a-bdf9b506706f)

Happened after trying to slice a model exported from fusion 360. 

Probable cause: After mirroring, Orca tries to create a temperary file next to the original one. Because unzipping or exporting creates a temporary file in their appdata folder, OrcaSlicer may be trying to create a file inside a folder that it cannot have an access to. 

Everything was working on 01.05.24 version of OrcaSlicer.
