### ISSUE TITLE
travel speed is overwrited by small perimeter speed in small perimters

### ISSUE THREAD

**Issue by gabwhoop** [SoftFever/OrcaSlicer#5355]
### Is there an existing issue for this problem?

- [ ] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

Windows

### OS Version

Windows 11

### Printer

Ender 3 custom SKR 1.4 Turbo

### How to reproduce

small perimeter = 12mm
travel speed = 200 mm

### Actual results

travel speed is overwritten by small perimeter speed in small perimeters.....

![20240513_072504](https://github.com/SoftFever/OrcaSlicer/assets/75207222/576236c3-e36b-4ffb-a8be-efbeccfeb958)
![20240513_072520](https://github.com/SoftFever/OrcaSlicer/assets/75207222/79ac6e9e-8ccc-4765-9180-a51bff4a254c)

### Expected results

better quality 
no strings 
reduce printing time

### Project file & Debug log uploads

[small perimeter test.zip](https://github.com/SoftFever/OrcaSlicer/files/15294297/small.perimeter.test.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by Dconn88** [comment]
I can confirm this is an issue and I found this on commenting instead of putting my own. (Sorry I'm new to git hub, but not to 3-D printing!) Just wanted to try to help built such an awesome product!

My small parameters are set at 50% speed, and when it prints all the screw holes simultaneously, the travel between the holes is a very taking 50% of my travel speed.
For example what I noticed is travel speed is set at 500 mm/s but it traveling around 250 mm/s in between small parameters when they are one after another. The preview still shows 500 mm/s when you look at the speed of visual, but actual is half of that, just in between small parameters. Everything else is great. 
I'm guessing it is about 250 mm/s based on my internal perimeters at 300 mm/s and external at 200 mm/s for my visual reference/calibration of eyesight, so that's why I am sure it's taking the 50% perimeter speed, and @gabwhoop's post confirms what I was thinking.

On the screenshot, shows 500 mm/s for all travel speed, but every travel between small perimeters ( screw holes) is visibly about half speed. Other travel is definitely 500 mm/s.

Thank you so much! Keep Up the good work!
![orca bug](https://github.com/SoftFever/OrcaSlicer/assets/91084593/8c04200a-10e5-4bd1-8294-4d8a8fc1f2eb)

**Comment by Dconn88** [comment]
Also, the same thing happens with travel speed on the 1st layer as well. My 1st layer travel speed is set at 50%, and my 1st layer speed is set at 50, 1st layer infill at 105. It should be doing 250 mm/s, but actual travel speed is about 50 mm/s. I think it's just taking the 50 from the initial layer speed.
