### ISSUE TITLE
Wall overflow problem

### ISSUE THREAD

**Issue by GlauTechCo** [SoftFever/OrcaSlicer#5397]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

macOS

### OS Version

14.2.1 Sonoma

### Additional system information

Macbook Air m1

### Printer

FlashForge M5p

### How to reproduce

Open 3mf project
When looking at the external walls from an angle, there are shifts

### Actual results

<img width="524" alt="Ekran Resmi 2024-05-19 14 52 28" src="https://github.com/SoftFever/OrcaSlicer/assets/33813227/1e7b25d2-cdc4-40e0-9793-a1c9bdc3e34a">

### Expected results

None

### Project file & Debug log uploads

[Test.3mf.zip](https://github.com/SoftFever/OrcaSlicer/files/15369254/Test.3mf.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by mtc1122** [comment]
Can you go back to the original and get a STEP file to see if it still does this (as much)?

This is a curved surface, which 3MF and STL can only estimate. These file formats define edges/walls/etc. with polygons and how to connect the points. Curves are not defined as curves, but instead lots of points connected with straight lines to estimate this curve. The software used to create the 3MF/STL file is also estimating where to put these polygons to get the best surface. Higher resolution, meaning more polygons, gives a better estimate at the expense of a larger file and more data to process. If you open that 3MF in modeling software, you're likely to see that the surface is bumpy when you zoom in enough.

STEP files define curves. What someone else can likely answer, is if OrcaSlicer handles curves from STEP files. I suspect it doesn't, only because it saves projects as 3MF files, but can't answer this definitively.

More importantly, how does it print?
