### ISSUE TITLE
Printer Change after importing a model resets all settings, even when clicking "Transfer" the profile settings

### ISSUE THREAD

**Issue by Nightshade09** [SoftFever/OrcaSlicer#5446]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

1.9.0

### Operating System (OS)

Windows

### OS Version

Windows 10

### Printer

BambuLab A1

### How to reproduce

1. Open any 3mf file from Makerworld
2. When opened, it selects the first printer that was on the makerworld page
3. when switching to your printer, it asks if it should discard, save or transfer the settings. 

### Actual results

When you click transfer, the settings dont get transfered, instead it switches the printer model but uses your own profiles instead of the one imported. This is especially unhelpful when using Hueforge models which are precisely sliced.

### Expected results

Profile Settings should get transferred

### Project file & Debug log uploads

[debug_Fri_May_24_17_43_01_14324.log.zip](https://github.com/SoftFever/OrcaSlicer/files/15436951/debug_Fri_May_24_17_43_01_14324.log.zip)
[project.zip](https://github.com/SoftFever/OrcaSlicer/files/15436954/project.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by rdbischoff** [comment]
Yeah, I wish that the 3MF that you download from Makerworld paid attention to what printer you selected on Makerworld or what printer you have open in the slicer. The 3MF has filaments and colors selected, but when I switch it from the X1C to my P1S, it sets all the filaments and colors back to what was set for the printer before I opened the 3MF. I want it to keep the filaments and colors so that I can then match them up with what I've got.
