### ISSUE TITLE
Embossed text and some other features disappear

### ISSUE THREAD

**Issue by Rickthebig** [SoftFever/OrcaSlicer#5488]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0

### Operating System (OS)

Windows

### OS Version

Windows 10

### Printer

DIY CoreXY (RRF)

### How to reproduce

Slice the model using the provided project file and inspect the result

### Actual results

Embossed text (which technically are holes) mostly disappear. The preview shows strange "empty" layers in some parts of the model (for example, in the cylinder). When actually printed, the embossed text is hardly recognizable on the surface, which is closed instead of open. There are other unusual details, like a partially filled hole (the embossed star). The half-sphere is completely missing.

### Expected results

Holes should be empty. "Ghost" layers should not appear with marks showing seams where the layers do not exist (but should). 
This is the model (cutout):
![image](https://github.com/SoftFever/OrcaSlicer/assets/151161212/53ec1d70-71a1-482d-b3f4-2ecf3aa4c72f)
This is what Orca slices:
![image](https://github.com/SoftFever/OrcaSlicer/assets/151161212/9fd66d9a-ae68-4cd7-a3c4-6be8bc3cad97)
This is what Cura slices and perfectly prints:
![image](https://github.com/SoftFever/OrcaSlicer/assets/151161212/9d636ad1-972d-40ca-8b4d-782c923f45d6)

### Project file & Debug log uploads

[3D_test_V3.zip](https://github.com/SoftFever/OrcaSlicer/files/15477189/3D_test_V3.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Anything else?

Trying to get the model sliced correctly, following things were tried:
Changing layer thicknes from 0.2 to 0.08 mm
Changing wall generator Arachne <-> Classic
Changing Slice gap closing radius from 0.5 to .02
Changing resolution from 0.12 to 0.06
Changing X-Y hole compensation to 0.4: Some letters reappeared, but holes are too wide then.
And some other things. Nothing helped.

**Comment by Avpman2** [comment]
Commenting so I can follow this thread. Having similar issues.

**Comment by Gozania** [comment]
commenting due to a similar situation...  Orca text embossing giving undesired results, where as Prusa functions correctly.  A bonus feature/function that no other slicer has would be the ability to specify the amount of lines/walls for text.

Orca Embossing
<img width="373" alt="Orca3 32" src="https://github.com/SoftFever/OrcaSlicer/assets/83924000/27f534f1-df80-47a6-aedb-cb797deefdbc">
<img width="398" alt="Orca3 35" src="https://github.com/SoftFever/OrcaSlicer/assets/83924000/6237563d-d113-4891-bb92-cdac6e4e47f4">

Prusa Embossing
<img width="441" alt="Prusa3 32" src="https://github.com/SoftFever/OrcaSlicer/assets/83924000/7ba51d17-1550-4faa-8d4b-87abbcbc217c">
<img width="411" alt="Prusa3 35" src="https://github.com/SoftFever/OrcaSlicer/assets/83924000/a5c4cacc-c6b8-4ceb-aa07-aaf392317ec1">

**Comment by Hunted05** [comment]
Also have this issue.  Annoying as I noticed it half way through a multiple piece print.  Please fix

**Comment by Gozania** [comment]
> Where is the "Only one wall on top surfaces" option located? tia

![Screenshot 2024-06-14 083726](https://github.com/SoftFever/OrcaSlicer/assets/83924000/36621628-4399-418d-9be7-ecbc2119a468)

**Comment by Avpman2** [comment]
I must be having a different issue. The option on my setup defaulted to unchecked.
