### ISSUE TITLE
Incorrect Overhangs

### ISSUE THREAD

**Issue by butchs38** [SoftFever/OrcaSlicer#5562]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

Windows

### OS Version

windows 10

### Printer

qidi xmax 3

### How to reproduce

load and slice

### Actual results

![image](https://github.com/SoftFever/OrcaSlicer/assets/53114645/fea3d3a2-1820-4c99-b348-567abe800e77)

### Expected results

Should not be a overhang line shows up in print

### Project file & Debug log uploads

[fb_l_dt2.zip](https://github.com/user-attachments/files/15531048/fb_l_dt2.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Anything else?

![image](https://github.com/SoftFever/OrcaSlicer/assets/53114645/9f148ed9-714a-429f-abfc-a6d333a25be8)
![image](https://github.com/SoftFever/OrcaSlicer/assets/53114645/0115cc40-273c-4935-8225-9cef9fb3dac7)

**Comment by SoftFever** [comment]
@butchs38 
This is caused by the X-Y hole compensation setting. In the bottom part, it is considered a hole, so it shrinks by 0.2 mm. On the rest of the part, it is not considered a hole; hence, it does not shrink. Because of this change, that layer is indeed an overhang. For this kind of model, X-Y compensation is not recommended.
![image](https://github.com/SoftFever/OrcaSlicer/assets/103989404/9524a254-9dbd-4134-85b0-82cf14f7526c)

**Comment by butchs38** [comment]
Thank you that fixed it. One more question on support why is one side different than the other almost hollow. The hollow support always fails. I have been using rec grid which works. Just wondering why it does this.
![image](https://github.com/SoftFever/OrcaSlicer/assets/53114645/51e423dd-757a-44ac-ad54-6ecb8ebe73de)
