### ISSUE TITLE
Start extrusion at nearest corner/point nearest purge line instead of long travel to start.

### ISSUE THREAD

**Issue by Gozania** [SoftFever/OrcaSlicer#5607]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

When I print my production parts with Orcaslicer, printing starts at the furthest corner from the purge line.  It would make more sense to travel less from the purge line and start the print at the nearest point from the purge line rather than a corner that is further away.  I tried to rotate the parts in hopes it would start where I would like, but it still starts in the furthest corner.

<img width="663" alt="Far Corner" src="https://github.com/SoftFever/OrcaSlicer/assets/83924000/3c2a5ac8-e1f2-49e4-9fcf-238beefce43b">

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

After the final purge line is drawn the extruder should move to the nearest corner/point of extrusion and begin printing there instead of a far part of the bed to start printing.  Ideally start at the red arrows for this given project.
<img width="663" alt="Far Corner Better " src="https://github.com/SoftFever/OrcaSlicer/assets/83924000/dcf99002-301a-48b8-8fe5-a9da80e86731">

### Describe alternatives you've considered

1. Re-orient part position but did not work.  Print starts in same place regardless of orientation.

**Comment by buzzhuzz** [comment]
I've also noticed that behavior some time ago and actually looked into the code.

The thing is:
- setting seam position to "nearest" makes print start at nearest corner, but seams are not aligned down a print. This is the only seam position method aware of tool head position as "nearest" seam placed as gcode generation filter
- any other seam position places seams on each object independently. In this case seam generator is not aware about environment like object position on the bed, tool head position and because of this we can't know position of purge line.
Also, aligned seam calculates metrics based on seam candidate visibility, overhangs and few other arguments which may result in seam placed in farthest or internal corner causing tool head travel over future perimeter line.
