### ISSUE TITLE
The slice process freezes when it reaches 65%, but the same model works well in Bambu Studio

### ISSUE THREAD

**Issue by BG9OXA** [SoftFever/OrcaSlicer#5617]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

Windows

### OS Version

Windows11

### Printer

Bambu lab p1sc

### How to reproduce

Here is my model file [https://github.com/BG9OXA/3D-printing/raw/main/model/Genshin_ExquisiteChest-gray_fixed2.3mf](https://github.com/BG9OXA/3D-printing/raw/main/model/Genshin_ExquisiteChest-gray_fixed2.3mf)
这是我的模型地址https://github.com/BG9OXA/3D-printing/raw/main/model/Genshin_ExquisiteChest-gray_fixed2.3mf

### Actual results

![屏幕截图 2024-06-07 154308](https://github.com/SoftFever/OrcaSlicer/assets/121809854/1eb38817-e0e5-4af0-8cdd-4ec09f7c4a19)

### Expected results

The slice process freezes when it reaches 65%
切片到65%后进程卡死不动了

### Project file & Debug log uploads

NO log

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by buzzhuzz** [comment]
The problem is indeed there: Tree support generation goes into infinite loop on layer 87, 88, 184 and 184. Which are the top interface layer and the void above it for the Lid and chest respectively.

You could workaround this issue by using Organic tree (somehow it works) or any type of Normal support.
