### ISSUE TITLE
Solid infill before internal bridges does not generate with "detect narrow internal solid infill" off

### ISSUE THREAD

**Issue by Ataraxia-Mechanica** [SoftFever/OrcaSlicer#5638]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.0-beta

### Operating System (OS)

Windows

### OS Version

Windows 10

### Printer

Voron 0

### How to reproduce

1. Disable "detect narrow internal solid infill"
2. Slice a 50mm cube

### Actual results

![image](https://github.com/SoftFever/OrcaSlicer/assets/111327195/3ab9e5ba-9359-4c4c-bd78-d4d4abbc2056)

Notice the sparse infill on the same layer got shifted inside and does not occupy the place where the solid infill should be.

### Expected results

![image](https://github.com/SoftFever/OrcaSlicer/assets/111327195/1e609e4f-e6df-42a4-b386-d790c5a76b34)

### Project file & Debug log uploads

[Cube.zip](https://github.com/user-attachments/files/15748249/Cube.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by Tanzelini** [comment]
This is still a bug in 2.2 and 2.3-dev as of today

**Comment by lin-xianming** [comment]
I took a look at the code and history of this line of solid infill under the bridge layer. It was developed in conjunction with conversion of narrow solid internal infill to concentric, and has never been intended to work without it. Prusa developed this feature for Prusaslicer, where disabling detect narrow internal infill is not an option.

The reason why it does not work with normal solid infill is that the the space is exactly the line spacing of solid infill, which is too narrow in many cases for solid infill to generate, especially with curves present. The narrow concentric infill does not behave like normal solid infill and can have variable line width, which is why it's possible to always generate the line correctly.

With detect narrow solid infill disabled, one of two things could be done.

1. Remove it entirely and don't shrink the sparse infill.

2. Increase the space so that normal solid infill will generate, which may work even better than Prusa's implementation, at the cost of some time.

<img width="1752" height="1435" alt="Image" src="https://github.com/user-attachments/assets/9d6131a6-1fcd-439e-8460-6c3a98c0ee58" />
