### ISSUE TITLE
layer 2 and 3 speed settings on the bridge

### ISSUE THREAD

**Issue by Br3n3n** [SoftFever/OrcaSlicer#5837]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Hello, I have a problem with the bridges. I would like to be able to adjust the speeds on the bridges. A layer that is already placed on the bridge layer so that the speed can be set. to make the final print better

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

adding the option to influence the speed of the layer that is printed on the bridge will improve the quality of the bridge. This function is already in slicer cura

### Additional context

![2,3bridge layer](https://github.com/SoftFever/OrcaSlicer/assets/173672256/dc8f120e-ac5a-4156-8edc-0d27b0a8b24c)

**Comment by stanpete78** [comment]
+1 Very helpful setting!

**Comment by digital0785** [comment]
this would be awesome!

also an option to go along with this is adding a bridge specific overlap setting so that way it can push further into the print 
this is just a temp tower but it basically just butts right up against it instead of overlapping so if you don't slow down enough it wont make good contact causing issues on subsequent layers :)

![image](https://github.com/SoftFever/OrcaSlicer/assets/74274738/83980dbf-ab04-4dd8-9ce8-b4515350e207)
