### ISSUE TITLE
sub folder under microSD card for Bambu printers

### ISSUE THREAD

**Issue by StephInoP** [SoftFever/OrcaSlicer#6075]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

no

### Which printers will be beneficial to this feature?

Others

### Describe the solution you'd like

to have a sub folder under microSD, so it looks organized

**Comment by kylek29** [comment]
I think that is going to need to be suggested at BambuLabs ( https://forum.bambulab.com/ ) since it's most likely a firmware level change.

Someone can correct me if I'm wrong, but the slicer is just sending the file to the printer -- or in Bambu's case, through the cloud to the printer. How it gets there and where it is stored is handled by the machine logic.

You can try the X1Plus firmware which has root access to the file system and FTP. That may let you add some structure.
