### ISSUE TITLE
Per-Linetype Speed Overrides should be available in filament settings

### ISSUE THREAD

**Issue by codeshaw** [SoftFever/OrcaSlicer#6107]
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

It is incredibly frustrating when changing filaments to need to alter both the filament properties and the process properties if specific linetypes need specific speeds.

The volumetric flow as a maximum is not appropriate in all cases.

Depending on the material line speed is just as important as retraction setting

I have searched for this issue and found it to have been closed multiple times often with no response other than "Yes, I would also like this feature"

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

Additional category added to `Filament Settings -> Overrides` with per-linetype options.

**Comment by kylek29** [comment]
I'm not sure why it hasn't been done in any of the slicers (I've seen it or similar suggested on Prusa as well). But I speculate it might be because (I think) they try to maintain the hierarchical order of how the settings are inherited, similar to a cascade approach. Machine/Nozzle -> Filament -> Process -> Object. Because the per line type settings exist in the Process, overriding from the Filament can confuse users who don't know (e.g. MakerWorld / .3mf imports) that the process is being overridden. 

If that is the case (again, speculation on my part, since no reasons have ever been stated for not allowing), they may need to add a checkbox next to the process settings for "allow Filament Overrides".

There's a few other settings that could use being added to the Filament section (such as ironing overrides).
