### ISSUE TITLE
FlashForge Adventurer 3 Custom line out of printing area for every file and calibration

### ISSUE THREAD

**Issue by GabrielJanucik** [SoftFever/OrcaSlicer#6282]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

Linux

### OS Version

22.04.4 LTS

### Additional system information

CPU: 13th Gen Intel® Core™ i9-13900H × 20
Memory: 96 GB
Graphic: NVIDIA Corporation / NVIDIA RTX 2000 Ada Generation Laptop GPU/PCIe/SSE2

### Printer

FlashForge Adventurer 3, 0.4 nozzle

### How to reproduce

1. Create new project
2. Calibration
3. Flow rate > Pass 1
4. Slice plate with default or any other presets
5. Export G-code file (That printer doesn't have network plugin in OrcaSlicer)
6. Try to print file using manufacturer app or USB stick

### Actual results

Got an error: "The printing file is out of the print range. The printer cannot print it".
In OrcaSlicer preview after slicing I can see thick straight line in start of printing. It appear always and for any file, not only in calibration. Line type shows it as "Custom".

### Expected results

No custom line or no nozzle travel outside the printing area
![Screenshot from 2024-07-29 11-18-55](https://github.com/user-attachments/assets/23034aa4-6432-47aa-b109-e4be2e4f1b3d)

### Project file & Debug log uploads

[debug_Mon_Jul_29_11_08_43_579660.log.zip](https://github.com/user-attachments/files/16410514/debug_Mon_Jul_29_11_08_43_579660.log.zip)
[Flowrate Test - Pass1.zip](https://github.com/user-attachments/files/16410520/Flowrate.Test.-.Pass1.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by GabrielJanucik** [comment]
Looks like I found an issue. I'm doing test print now and I will see how it goes. Eventually I will creat pull request with fix for that.

**Comment by EXE-g** [comment]
I'm confirming the problem. The problem has not been solved. Can't use G-code from OrcaSlicer because of an unknown generated line outside the table.
![issue](https://github.com/user-attachments/assets/c8e1bac4-b7f8-40bf-ba7b-8774da108317)

**Comment by EXE-g** [comment]
I'm confirming the problem. The problem has not been solved. Can't use G-code from OrcaSlicer because of an unknown generated line outside the table.
![issue](https://github.com/user-attachments/assets/a9a9e0ae-0f2d-4baf-8c7c-5a8d1556f72f)

**Comment by chernser** [comment]
@EXE-g 
Same problem. Fixed by changing start G-Code to 
```
G1 X-37.50 Y-65.00 F6000
G1 X37.50 Y-65.00 E9.5 F1200
``` 

This is very "safe" offset, so for bigger models it should be something: 
```
G1 X-37.50 Y-70.00 F6000
G1 X37.50 Y-70.00 E9.5 F1200
```

**Comment by dbaarda** [comment]
I'm also experiencing this problem. I'm guessing this is because somewhere in the printer config it says that the print volume is X=-75->75mm,Y=-75->75mm,Z=0->150mm, which is what the printer specs say, and this means the generated gcode for the pre-extrude looks like this;

```gcode
...
;pre-extrude
M108 T0
G1 X-37.50 Y-75.00 F6000
M106
G1 Z0.200 F420
M73 P1 R12
G1 X-37.50 Y-74.50 F6000
G1 X37.50 Y-74.50 E9.5 F1200
...
```

The bit drawing the line between (-37.50,-74.50,0.200) to (37.50,-74.50,0.200) is inside the limits, but not when you take into account the pre-extrude line width, which for E=9.5mm, Z=0.20 over a line length of 75mm works out as w=1.52mm. That means the outside edge of the line is at -(74.5 + 1.52/2) = -75.26mm. The move before that to (-37.50,-75.00) also goes right to the print volume limit, but the print volume limits are inclusive so that is not a problem.

It looks like GabrielJanuciko@ tried to fix this in #6744 by bringing the extrude draw just inside the y=-75.00 limit but didn't go far enough to compensate for the line width. They also missed fixing the move before the hopdown, which would normally go to the position directly above the line start before the hop-down, but that's not the cause of this problem. 

I've tested this by editing the pre-extrude line draw to be on Y=-174.20 and it works fine, even with the move before still going to Y=-75.00. However, IMHO to be safe it would be better to use Y=-174.00 and also fix the move before the hopdown. I note that all of these are defined in the `machine_start_gcode` string reported in comments in the generated gcode, and it looks like an easy fix to the `resources/profiles/Flashforge/machine/fdm_adventurer3_common.json` printer config file.

**Vaguely related;** FlashPrint always emits the following as the very first command in its generated gcode;

```gcode
M118 X<xmax> Y<ymax> Z<zmax> T0
```

Where `<xmax>`, `<ymax>`, and `<zmax>` are the maxium absolute X, Y, and Z positions in the following gcode. This establishes a bounding box for the print job's print volume. The printer will reject the print if this exceeds the printer's print volume **or** if any command in the gcode exceeds those positions. In my script-generated gcode I always just send `M118 X75.00 Y75.00 Z150.00 T0` to establish the limits at the full print volume. I don't think there are any benefits to setting it more tightly constrained to the print job other than sanity checking your generated gcode. I note that orca is not emitting this in its generated gcode.

I'm not sure if these limits persist after a print or if they are reset between print jobs. If they persist, it's possible a print job without this command could be bound by the limits set in an earlier print job that did set these limits. This might explain what is happening if people are finding rebooting the printer can fix intermittent print failures. Perhaps adding this to the `machine_start_gcode` to be safe is a good idea.

I would re-open this issue because it's still unresolved except I don't have permission.

**Comment by dbaarda** [comment]
Note this was fixed in https://github.com/SoftFever/OrcaSlicer/pull/9726 which is not yet in the official release v2.3.0, but is in the v2.3.1 aphas. However that fix only addressed the serious "out of build volume" problem and doesn't include any of the more minor things l noted like;

1. The hop-down is not over the start of the pre-extrude line.
2. There is no initial `M118` line (but this is not important?).

There are also other minor problems like;

1. It unconditionally turns on the enclosure (`M651 S255`) and extruder (`M106`) fans regardless of settings.
2. The `machine_end_gcode` turns off the enclosure fan `M652`  but not the extruder (`M107`) fan.

Note that these are mostly minor except that the Adv3 doesn't correctly understand the fan commands OrcaSlicer emits in it's generated gcode because;

1. It doesn't understand the `S<0-255>` speed argument to `M106`, and can only turn the extruder fan full on. So `M106 S0` doesn't turn off the extuder fan. Only `M107` will turn the extruder fan off.
2. It doesn't understand the `P<1-3>` fan selection argument to `M106`, and I think just ignores them. So `M106 P<2-3> S<0-255>` will not set the speed of the enclosure fan. Only `M651 S<0-255>` will set the enclosure fan speed and `M652` will turn it off.
3. It ignores any line with a comment `;` anywhere, so it ignores gcode commands with trailing comments.

This means the Adv3 ignores nearly all of the fan speed setting commands Orca generates, making setting them to the desired values in the start and end gcode more important. Personally I use these machine gcode fragments and post-processing script to modify the generated gcode to better suit the Adv3;

* https://github.com/dbaarda/workspace-tools/blob/main/3DPrinting/Adv3_machine_start.gcode
* https://github.com/dbaarda/workspace-tools/blob/main/3DPrinting/Adv3_machine_end.gcode
* https://github.com/dbaarda/workspace-tools/blob/main/3DPrinting/Adv3_layer_change.gcode
* https://github.com/dbaarda/workspace-tools/blob/main/3DPrinting/toadv3.sh

**Comment by Julien-tx** [comment]
Hi,

Thank you for the share and work done on that and I realy like my adv3 printer and I would like to better printing.

But following your work, I got some trouble to apply the post processing script. I'm on Windows / Orca Slicerr 2.3.0 .
I put the file path : C:\TEMP\adv3.sh; then when I do the export , i'm getting : win32 error 193

Could you please give me some advice to apply it successfully ?

**Comment by dbaarda** [comment]
> Hi,
> 
> Thank you for the share and work done on that and I realy like my adv3 printer and I would like to better printing.
> 
> But following your work, I got some trouble to apply the post processing script. I'm on Windows / Orca Slicerr 2.3.0 . I put the file path : C:\TEMP\adv3.sh; then when I do the export , i'm getting : win32 error 193
> 
> Could you please give me some advice to apply it successfully ?

Ahh... the problem is almost certainly that my `toadv3.sh` script is a unix bash script that invokes the unix `sed` command to post-process and edit the gcode, and these tools don't exist on windows by default. It is possible to install them using things like Cygwin, and I've seen comments online that sed does exist for windows, but you might need to fiddle with things to make them work. There is also a possiblity that Unix vs DoS line endings in the text files could confuse things. If you could get a Windows sed command working, it should be fairly straight-forward to convert the bash script into a *.bat file if you needed to.

On Linux it just works.

I should also be possible to rewrite the post-processing script in Python, which may make things easier on windows. It's actually a pretty simple...
