### ISSUE TITLE
Purge tower going mad with variable layer height

### ISSUE THREAD

**Issue by Alkerion** [SoftFever/OrcaSlicer#6350]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

Windows

### OS Version

11

### Printer

Bambu X1C

### How to reproduce

1. add an object with several colors
2. apply some variable layer height to the object
3. slice

### Actual results

The purge tower is far too big and go outside plate.

![Capture d’écran 2024-08-05 133206](https://github.com/user-attachments/assets/607cfa8b-d9c9-441d-ac07-ce846c940c1b)

### Expected results

Correct purge tower dimensions

### Project file & Debug log uploads

[purge tower.zip](https://github.com/user-attachments/files/16495587/purge.tower.zip)

### Checklist of files to include

- [ ] Log file
- [x] Project file

**Comment by MermaidSystem** [comment]
I have the same Problem, it seams there is a Problem with the layer height calculation.
There is a Layer with a thickness of 0.00mm (Layer 98 is at 11.84mm and Layer 99 ist at 11,84mm too) and at his layer it gets this extreme broad purge block.

I think, because the progeblock is defined by volume, this causes a division by zero.

those funky Layers happens only, when i have two or more objects on the build plate. when i'm slicing both objekts on different plates, everything is fine,
Even with no colore changes, i'll have these 0,00 or 0,01mm layers with two objects on the buildplate.

When i'm alligning the standard layer hight from 0,12 to 0,1 (My model is metric) to my model everything is fine.
