### ISSUE TITLE
False object "too tall" warnings in By Object print mode

### ISSUE THREAD

**Issue by otede** [SoftFever/OrcaSlicer#6876]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.1

### Operating System (OS)

Windows

### OS Version

Windows 10

### Additional system information

intel i3 32 GB RAM

### Printer

Bambu Lab A1

### How to reproduce

1. Load several object that should obviously fit in one print run.
2. Select By Object Printing mode

### Actual results

A warning sometimes pops up: Object <object_name> too tall, and collisions will be caused.

### Expected results

No such warnings as above, allow to slice, clear the gantry over any objects as necessary based on the printer profile gantry height given. The XY contour should be the only limiting factor for objects of height much less than the Z volume limits. 

### Project file & Debug log uploads

[Orca issue otede object too tall bogus warning.zip](https://github.com/user-attachments/files/17090822/Orca.issue.otede.obj
[20240922 log.zip](https://github.com/user-attachments/files/17090827/20240922.log.zip)
ect.too.tall.bogus.warning.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Anything else?

Related issue has been closed.
https://github.com/SoftFever/OrcaSlicer/issues/3299

**Comment by Noisyfox** [comment]
You can always raise the "height to rod" value to your z limit and use it at your own risk. Slicer cannot gaurantee such clearance and plan a safety travel path for you, for example if your printer marco does anything stupid etc.

**Comment by otede** [comment]
> You can always raise the "height to rod" value to your z limit and use it at your own risk. Slicer cannot gaurantee such clearance and plan a safety travel path for you, for example if your printer marco does anything stupid, or if you place your models parallal to the gantry etc.

I spent a solid year using Cura. No such issue was present. Any object could be printed in multi as long as both conditions were met:
1. Lack of XY contour collision
2. Objects' height less than Zmax - Gantry_height

**Comment by Noisyfox** [comment]
> > You can always raise the "height to rod" value to your z limit and use it at your own risk. Slicer cannot gaurantee such clearance and plan a safety travel path for you, for example if your printer marco does anything stupid, or if you place your models parallal to the gantry etc.
> 
> I spent a solid year using Cura. No such issue was present. Any object could be printed in multi as long as both conditions were met:
> 
> 1. Lack of XY contour collision
> 2. Objects' height less than Zmax - Gantry_height

![image](https://github.com/user-attachments/assets/9eaa9406-dd4c-413e-93e5-f891f555d3d6)
How would you ever print such arrangment in print-by-object mode using a core-xy printer without the gantry crashing into the first object?

**Comment by otede** [comment]
> How would you ever print such arrangment in print-by-object mode using a core-xy printer without the gantry crashing into the first object (assuming you don't have a 20+cm long nozzle)?

Who said anything about core-xy? You can see above I stated BL A1 which is a bed slinger. And my old Cura powered scrap printer was also a bed slinger.

**Comment by Noisyfox** [comment]
And:
![image](https://github.com/user-attachments/assets/8acbdd45-fc6d-4538-9ffa-a54d74c12cd2)

**Comment by Noisyfox** [comment]
> > How would you ever print such arrangment in print-by-object mode using a core-xy printer without the gantry crashing into the first object (assuming you don't have a 20+cm long nozzle)?
> 
> Who said anything about core-xy? You can see above I stated BL A1 which is a bed slinger. And my old Cura powered scrap printer was also a bed slinger.

Oh? Do you mean you could print that on an A1?

**Comment by otede** [comment]
> Oh? Do you mean you could print that on an A1? You do realize it still have an X axis right?

If only you spent as much energy for evaluating the problem as you do playing a smarty pants. [pic22] Not only you went with an absolute extreme example, you also deliberately oriented the objects along the Y axis without the actual need to do so. In such a case it IS impossible to not have a collision. In my example - it is possible. [edit: It's simply out of the slicer feature set].

The Cura exmplanation popup is not clear. However I've just checked and I was indeed wrong with regard to Cura being satisfied with just meeting the "Objects' height less than Zmax - Gantry_height". It's just that my old printer had a gantry height some 2 times bigger than A1. Hence I routinely printed setups like this [example22].

I went ahead and filled Orca's plate with objects lower than my A1 gantry height of 25 mm and it let me slice.

I guess now we're in the "wishlist" area now as the currect behavior is "it is what it is." 

[pic22]
![irfan_20240923_173241](https://github.com/user-attachments/assets/1c9b2df6-7795-4e2c-bd37-4c00edb4ff7a)


[example22]
![irfan_20240923_180501](https://github.com/user-attachments/assets/d6a55568-cc64-494b-b7fa-725b174de242)

**Comment by otede** [comment]
I've just discovered Prusa has already implemented some smarter algorithms for the purpose.
![irfan_20241016_191248](https://github.com/user-attachments/assets/9269df96-fd86-4452-b5d2-ba625dc57f07)

**Comment by TheOverpassArsonist** [comment]
Sorry to potentially necro this but why was it marked as completed? Currently having a somewhat similar issue (I want to do a 'by objects' print with one short lid and one very tall container, which should easily by possible by printing the lid first THEN printing the container itself, but Orcaslicer is complaining that the container is too tall) and it seems like this was marked as 'complete' even though the comment immediately before that happened gave no indication of it being addressed.

<img width="1176" height="574" alt="Image" src="https://github.com/user-attachments/assets/51d985a1-0f98-4c9e-8e78-c32d711cb3bb" />

Correct me if I'm wrong but a more 'complete' algorithm here would be sort of what's suggested here except checked incrementally by iterating through every object. E.g. : you can print an arbitrarily large number of short things, but only one tall thing. (because once the tall thing is printed, that interferes with future gantry movements) This has an exception if you carefully order your objects such that in printing each new one the gantry would never have areason to push over the other ones. (though on a raising bed design instead of a flying gantry design there is still an upper-height limit before the past prints physically hit the roof of the printer - if it's enclosed at least)

This actually raises an interesting alternative print mode, 'chunk by chunk' printing, where it goes object by object in multi-layer segments, then wraps back around. So it prints 20 layers of object 1, 20 layers of object 2, 20 layers of object 3, 20 more layers of object 1, 20 more layers of object 2, 20 more layers of object 30, etc. This would be a middleground between both layer by layer and object by object that still minimizes stringing, unnecessary travels, etc. without as many geometric considerations necessary. (for instance there would be no additional height limit, since at a macro-scale it's still going layer by layer, it's just working in multi-layer chunks)

**Comment by otede** [comment]
@Azio-Pantheon Re chunks - you can already achieve this by using Assembly in right click menu.

**Comment by Ovaday** [comment]
Same on Flow Calibration - default Klipper Settings:

<img width="1060" height="793" alt="Image" src="https://github.com/user-attachments/assets/35487440-009a-41c5-849d-2984313d481b" />
