### ISSUE TITLE
X-Y hole/contour compensation creates unexpected inner wall shrink

### ISSUE THREAD

**Issue by broxinagil** [SoftFever/OrcaSlicer#736]
Setting X-Y compensation (either hole or contour) creates unexpected shrink on inner walls on certain layers, where e.g. holes are in the model. This does not affect outer walls. This issue is as well seen on original Bambu Studio 1.5.0.61 and Softfever 1.4.4.

**with compensation:**
![image](https://user-images.githubusercontent.com/4527335/231409234-647dcf2a-c021-4e94-8794-d69efd0ea569.png)

**without compensation:**
![image](https://user-images.githubusercontent.com/4527335/231409470-b67a0bee-dfa6-43b4-9394-5c4dfe6809e9.png)

**Comment by kevinakasam** [comment]
Bump on this, just got the same issue today. Used latest version 1.6.1


![4624B347-15B9-4829-9EEE-0C5F9037568E](https://user-images.githubusercontent.com/74542463/231750059-f733abf9-49c7-45da-abe1-587c69777df0.png)
![181768B8-4984-4FCA-8363-38F09ECCED2B](https://user-images.githubusercontent.com/74542463/231750071-0339578f-675d-40d6-b0f4-e5fd7ad626b5.jpeg)
![4012B2E5-CC3B-4420-97C3-3872EE2C60D0](https://user-images.githubusercontent.com/74542463/231750078-5a6664b3-b158-456f-a728-dc2447c30a15.jpeg)

**Comment by SoftFever** [comment]
Can you share a sample project?

**Comment by broxinagil** [comment]
[LampWZ.zip](https://github.com/SoftFever/OrcaSlicer/files/11238735/LampWZ.zip)
Here it is

**Comment by osmanoney** [comment]
X Y compensation should be used as an active value and there should not be that much protrusion. this is a big problem.stl file is attached

**Comment by NexGen-3D-Printing** [comment]
Im also seing major issues with this feature, including the inner wall shinkage near holels, its cuasing all sorts of anomlies in prints, I have opted to disable it for now, using scale to compensate for material shrinkage might work better.

**Comment by osmanoney** [comment]
prusa does not give such an error either. as a result, this is an error in orca and should be corrected

**Comment by SoftFever** [comment]
When a vertical hole is present, the algorithm fails to detect horizontal holes because, technically, they are no longer considered holes.

PrusaSlicer doesn't have a hole compensation feature. Instead, its XY size compensation is equivalent to Orca's shrinkage feature. You can use this as a workaround.

![Screenshot 2023-11-11 at 10 19 47 AM](https://github.com/SoftFever/OrcaSlicer/assets/103989404/f33e7155-aa51-4a34-a650-5e1e8c47f6a5)

![Screenshot 2023-11-11 at 10 10 36 AM](https://github.com/SoftFever/OrcaSlicer/assets/103989404/5e36a1cc-fda2-4802-a23d-cd54009331d5)

**Comment by gbkwiatt** [comment]
@SoftFever Will this ever be fixed/corrected or accounted for with different feature, or  "it is what it is" ?
