### ISSUE TITLE
Regression on 2.2.0 causing underextrusion

### ISSUE THREAD

**Issue by philip-soerensen** [SoftFever/OrcaSlicer#7633]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.2.0

### Operating System (OS)

Linux

### OS Version

Arch Linux

### Printer

Ankermake M5C

### How to reproduce

0) Start with an install of Orcaslicer 2.2.0
1) Setup an Ankermake M5C with 0.4mm nozzle using the unmodified preset profile
2) Choose a preset filament profile (confirmed for "Anker Generic PLA+" and "Anker Generic PETG") 
3) Slice any model (defect is most apparent in prints with many starts and stops such as ones with fine separate structures)
4) Send the gcode to the printer through any method and print

### Actual results

Serious defects, similar to under extrusion, appear whenever the extrusion restarts after travel.
After some millimetres or centimetres, the normal flow appears to restart, but the first few mm will be barely extruded if at all. This ruins the print quality to the point of breaking, although the print may still complete.

### Expected results

A nice print without defects, as seen in V2.1.1.

### Project file & Debug log uploads

Project file:
[project_file.zip](https://github.com/user-attachments/files/17970361/project_file.zip)

I don't think there is anything interesting in the log since nothing is visibly wrong in the slicer, only in the printed object.
Nevertheless, it is attached here:
[debug_Sun_Dec_01_22_09_38_31951.log.0.zip](https://github.com/user-attachments/files/17970366/debug_Sun_Dec_01_22_09_38_31951.log.0.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Anything else?

The problem is specific to V2.2.0. The problem is resolved by using V2.1.1 with the same settings (as far as I can tell).  Here is a comparison with a test print done on the two versions where the regression is clearly visible in the V2.2.0 version:
![Specific to V220](https://github.com/user-attachments/assets/e675d789-f4ba-4c0b-a67d-e465b6e63de2)

Here is a closeup on a bigger print showing the defect in more detail: 
![IMG_20241127_093240](https://github.com/user-attachments/assets/54259531-bdaa-4069-914a-cc7d7626da76)

The problem has been reported by other users (also printing on Ankermake M5C as far as I know) and I have reproduced the behaviour with a fresh install of Orcaslicer on a completely different computer. I have also confirmed that it appears with several different filaments (both PLA+ and PETG). The fact that the prints are perfect when sliced with V2.1.1 or with any other slicer confirms that there is nothing wrong with either the filament or the printer itself.

**Comment by Xelinor** [comment]
@SoftFever it looks like a change was put in here:

https://github.com/SoftFever/OrcaSlicer/commit/296b234fe6d6a5f2323c97ad0cf21e3ec21c931e

Why was this change made? Those settings are not what was intended and validated with the rest of the profile.

**Comment by philip-soerensen** [comment]
By the way, [staal54a](https://github.com/staal54a), we discovered the changed settings because you prompted me to put the gcode through a diff tool. So, thanks for your comment! Unfortunately, this seems to be isolated to the Ankermake profiles, so I guess it won't help you with the issue you quoted, although the symptoms are similar.

**Comment by robertbaker** [comment]
The issue is the M5 and M5C share the same profile and have different values. Reverting back isn't a proper solution because then the M5 would now be restricted by the M5C limitations when it can run faster. I apologize for missing this discrepancy.

The proper solution would be to only have the shared values between both printers in the common profile and create profiles for each printer so they both have their proper values.

Here is the values taken from AMS 1.5.24 (latest as of writing) for both printers:

![m5-extruder](https://github.com/user-attachments/assets/26b2924e-4c38-4815-9212-709248fb2503)
![m5-general](https://github.com/user-attachments/assets/3f50f13b-6478-47b4-b42b-2e022e3710b8)
![m5c-general](https://github.com/user-attachments/assets/3cbe99fb-604e-49c2-a4bf-e1d34234284a)
![m5c-gcode](https://github.com/user-attachments/assets/12564e94-a5a8-4d61-a717-795978511e4f)
![m5c-extruder](https://github.com/user-attachments/assets/34300567-369d-435d-9bf5-becc08e31842)
![m5c-machine-limits](https://github.com/user-attachments/assets/42981e98-90c0-4eed-ac2c-12848300e8a8)
![m5-gcode](https://github.com/user-attachments/assets/950ce5e3-f0ef-4913-b676-9debc0523ca2)
![m5-machne-limits](https://github.com/user-attachments/assets/c95d72cc-d874-4508-8a2b-a16877022615)

**Comment by robertbaker** [comment]
> Have you tried looking through the resulting gcode files for the same object from both versions to see if there is any noticeable difference in some of the extrusion values being used? The only other step I would recommend is to definitively go in and verify if there are any settings differences between the profiles in the different versions via side by side comparison of the settings.
> 
> I tried to recreate with your steps in each of the versions called out using one of the retraction tests with the four square columns and didn't see anything that would majorly jump out in the gcode to me but I also don't have an M5C so I couldn't print them.
> 
> The main reason I'm potentially interested in this ticket is it sounds like there could be some overlap with this ticket related to wide seam gaps: #6378
> 
> The issues with restarting after retraction seams to be a common theme between these two bugs so it may be somewhat related.

I'm thinking matching the profile values to what AMS has (and AMS obviously prints fine) means this is a red herring and not the actual cause why M5C owners are having an issue is something else.
I also noticed the seam gap issue on my M5.

The values were updated to match what AMS has, so I don't see how this could be the cause unless the values displayed in AMS are bogus and anker hides the real values it could have hardcoded.

I will install the old slicer and see what the values were for each printer before they swapped to AMS.

I only have an M5 and I tested this with various prints before making a PR. Since the values were the same for the M5C, I didn't forsee an issue with the M5C. Since the values between the 2 printers, match, I'm thinking something else is the cause.

For owners of the M5C,
Using version 2.2, make a copy of the M5C profile and change the values back to the 2.1 values and do the same print and see if it actually fixes your issue. If it doesn't, that means it's something else entirely and not an issue with the values update I did, which just matches what is provided by anker in the AMS

**Comment by robertbaker** [comment]
![M5C  4 extruder](https://github.com/user-attachments/assets/ecb7cb96-2785-4e39-a243-59fbb34407c7)
![M5  4 extruder](https://github.com/user-attachments/assets/31326c16-32a1-40b0-9ddc-8d4adb5c673b)

![M5c  2 extruder](https://github.com/user-attachments/assets/afd1424e-eeea-45d8-a3a6-542d4ff33713)
![M5  2 extruder](https://github.com/user-attachments/assets/bd5401cb-3145-4c92-b569-97fdf684d056)

![M5c  8 extruder](https://github.com/user-attachments/assets/c0419c5d-f695-4c32-85d6-dfcf9a53227f)
![M5  8 extruder](https://github.com/user-attachments/assets/da8b539c-815d-4c6c-a1f5-17d397a03902)

![M5c  6 extruder](https://github.com/user-attachments/assets/3efaa061-d1b0-4fe1-a044-f79ff7cb5c10)
![M5  6 extruder](https://github.com/user-attachments/assets/286517f4-899a-49af-b596-d0b87e02fd4e)

**Comment by Xelinor** [comment]
> > @SoftFever it looks like a change was put in here:
> > [296b234](https://github.com/SoftFever/OrcaSlicer/commit/296b234fe6d6a5f2323c97ad0cf21e3ec21c931e)
> > Why was this change made? Those settings are not what was intended and validated with the rest of the profile, and I suspect this is what is causing the regression.
> > I haven't had time to check against other settings, so maybe there's other changes too?
> 
> This change was made because it didn't match the latest values provided in AMS.
> 
> This issue does not happen on the M5. reverting the values would artificially limit the M5 just to fix the M5C. Not sure why the M5C has an issue since both values are the same between the 2 in anker's slicer. Which makes me think this change exposed a different problem with the M5C.

Your assumption is that it limits the M5, which is incorrect. The M5 ignores a lot of gcode commands that the M5c does not, which is what is actually going on here. Anker does a lot behind the scenes with that machine that amounts to a lot of smoke and mirrors, like putting in artificially high jerk limits. If you actually do Jerk testing with the machines, like I have, you will find that the belt tension can't handle those settings and it needs to be set lower, which is one of the things I did when I overhauled the settings in Orca a while back. We did a LOT of testing and validation when we came to those settings, and we did it on both the M5 and the M5c. The M5c accepts quite a few standard marlin commands that the M5 ignores, which IS what is happening here.

In the end, changing it to what Anker claims is the machine limit doesn't really make sense anyway. The M5 is limited by its hot end.

The M5's volumetric flow rate, at best, is around 18mm³/s. You can get it higher by printing well over the tolerances of the material you are printing, but you will suffer in ability to retract material and so print quality basically goes to hell. At 18mm³/s, you are NEVER hitting anywhere close to the machine limits Anker claims the M5 can go to in those limits, so it simply didn't make sense to bring them along.
