### ISSUE TITLE
no display bedshape screen 

### ISSUE THREAD

**Issue by salocain** [SoftFever/OrcaSlicer#787]
![Capture d’écran du 2023-04-18 23-38-48](https://user-images.githubusercontent.com/72736639/232911709-02e6e5c1-d996-41b0-a05c-3f9b634fd120.png)
![Capture d’écran du 2023-04-18 23-41-51](https://user-images.githubusercontent.com/72736639/232911732-171e5770-dd8d-4da9-815d-87dbed755752.png)
all is displayed exept the right screen part (the bed screen)
but before , with an old version (1.42)it's worked , but after this version  ..no  

![Capture d’écran du 2023-04-18 23-24-13](https://user-images.githubusercontent.com/72736639/232908774-d868c469-c4fa-4374-a9e7-8d50c6970624.png)

**Desktop (please complete the following information):**
 - OS: linux mint

**Comment by SoftFever** [comment]
Hi @salocain ,
Looks like a graphics drivers issue.

Anyway, try modifying the ~/.OrcaSlicer\system\Artillery\machine\Artillery Sidewinder X2.json file and remove the bed texture to see if that fixes the issue for you.
![image](https://user-images.githubusercontent.com/103989404/233114098-02c39699-9f86-43aa-99b9-a7d5a4a531e5.png)

**Comment by salocain** [comment]
i don't understand why you talking about artillery machine ...

but... i go to  ~/.config/OrcaSlicer/system/ my machine / remove the bed texture in config texte file --->same issue

if it's a driver problem why the 1.4.2 works and the after release not..

**Comment by SoftFever** [comment]
Somehow I mis-read it as Artillery.
Honestly I have no idea why 1.4.2 works but 1.6.2 don’t.

**Comment by docemiel** [comment]
Good afternoon, After reading that it could be a graphics problem, I decided to change the pregnant drivers instead of using the nvidia ones, I opted for the open-source ones... and now it works! thanks for the tip

![Captura de ecrã de 2023-04-22 13-45-14](https://user-images.githubusercontent.com/105605043/233786416-b5757068-2ca1-47a7-80a5-4ca420203ef8.png)
![Captura de ecrã de 2023-04-22 14-03-37](https://user-images.githubusercontent.com/105605043/233786467-24ff4f4c-6ffe-496c-a33d-d6687e896fd1.png)

**Comment by salocain** [comment]
yes , it's a graphic driver problem , i do exact same thing has you , i switch to the open source driver instead the nvidia driver --> and it's work ^^

it's the same driver (390)
