### ISSUE TITLE
FLSUN V400 build plate is barely visible in dark mode, solution proposed

### ISSUE THREAD

**Issue by tokamac** [SoftFever/OrcaSlicer#825]
The default FLSUN V400 PEI build plate is barely visible against the background in a dark mode environment, while the FLSUN logo pops out so much it makes my eyes bleed:

![FLSUN-V400-default-buildplate](https://user-images.githubusercontent.com/3685009/233779168-96730f05-a144-4802-83fc-ae2f292db2c5.jpg)

Solution proposed: use a more contrasted image for the build plate, as well as a less contrasted (less distracting/annoying) FLSUN logo. May I suggest to use my own custom Golden PEI build plate made for PrusaSlicer. Available here: https://www.printables.com/model/330855-flsun-v400-golden-pei-buildplate-texture-for-prusa/files

![FLSUN-V400-custom-buildplate](https://user-images.githubusercontent.com/3685009/233779411-4e9e5471-5d6c-4ea1-a854-44aaeb6a99fc.jpg)

It works well in both light and dark modes, as is without any modification in OrcaSlicer other than replacing directly the file at
`OrcaSlicer/resources/profiles/FLSun/V400.svg`
Plus it looks more like the real thing IMHO.

**Comment by Guilouz** [comment]
@SoftFever Can you replace stl texture by mine : [V400_bed.stl.zip](https://github.com/SoftFever/OrcaSlicer/files/11327439/V400_bed.stl.zip)

With yours:

<img width="2560" alt="Capture d’écran 2023-04-26 à 01 05 34" src="https://user-images.githubusercontent.com/12702322/234426458-899e03eb-dc54-4a41-b61c-c8ac7b79b66a.png">


With mine that does not block the view caused by towers:

<img width="2560" alt="Capture d’écran 2023-04-26 à 01 04 46" src="https://user-images.githubusercontent.com/12702322/234426488-db060b7b-83ed-487e-a7cf-4242458bfe53.png">

<img width="2560" alt="Capture d’écran 2023-04-26 à 01 04 36" src="https://user-images.githubusercontent.com/12702322/234426499-e764fce4-6302-43ae-94c4-71395ff9505e.png">
